var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
var UWL_VERSION="1.002",TYPE_CPU_SERVER="F",HDTYP="Content-Type",HDVAL="application/x-www-form-urlencoded",CGI_HOST="",CGI_RD_DEV_RND=CGI_HOST+"/cgi/RdDevRnd.cgi",DEF_TIMEOUT_MIN=5,MAX_BLOCK_NUM=32,KEY_WS_DATBLK="WSDatblk",KEY_WS_LEVEL="WSLevel",KEY_WS_FIGURE="WSFigure",KEY_WS_PICTURE="WSPicture",KEY_WS_HSTGRP="WSHstgrp",KEY_WS_WTR_BTN="WSWtrBtn",KEY_WS_LOGOUT_BTN="WSLogoutBtn",ID_ERR_SUFFIX="_Err",ID_ERR_DISP_BTN_SUFFIX="_ErrDispBtn",CLASS_SINGLE_MESSAGE="single_message",CLASS_PARTS_BASE="partsBase",
CLASS_GLOBAL_MESSAGE_AREA="globalMessageArea",CLASS_ERROR_MESSAGE="errorMessage",CLASS_ERROR_FIELD="errorField",CLASS_ERROR_BUTTON="errorButton",PARTS_MAX=1,updateInterval=null,dspLanguage=null,logoutPartsList=[],popupFlag=0,timerID_W10=0,HTTPcloseTM_W10=9999999;
QueTable=function(){function a(a,b){var c=0,d=0;try{for(key in a){for(d=0;d<b.length;d++)if(Object.keys(b[d]).length+a[key].length>MAX_BLOCK_NUM){if(!(d+1 in b)){d++;b[d]={};break}}else break;for(var e=0;e<a[key].length;e++)c++,b[d][key+"_"+e]={partsId:a[key][e].partsId,serialNo:a[key][e].serialNo,partsType:a[key][e].partsType,devName:a[key][e].devName,devType:a[key][e].devType,keepObj:a[key][e].keepObj}}}catch(n){console.log("[ "+n.message+" ] "+n.stack);debugger}return b}var b=[],c=[],d=function(){return{get:function(){return Object.keys(b).length}}},
f=function(){return{get:function(){return Math.ceil(this.length/MAX_BLOCK_NUM)}}},g=function(){return{value:function(a,c,d,e,f){try{a in b||(b[a]=[]),b[a][0]={partsId:a,serialNo:0,partsType:c,devName:d,devType:e,keepObj:f}}catch(n){console.log(n.message)}}}},e=function(){return{value:function(a,b,d,e){try{a in c||(c[a]=[]);for(var f=0;f<d.length;f++)c[a][f]={partsId:a,serialNo:f,partsType:b,devName:d[f][0],devType:d[f][1],keepObj:e}}catch(n){console.log(n.message)}}}},k=function(){return{value:function(){var d=
[],e=[],f=0;d[0]={};e[0]="";d=a(c,d);d=a(b,d);tempcnt01=tempcnt00=0;try{for(var g=0;g<d.length;g++)for(key in tempcnt00++,f=0,e[g]="",d[g])e[g]+="&DEV"+(f+1)+"="+d[g][key].devName+"&TYP"+(f+1)+"="+d[g][key].devType,f++,tempcnt01++;for(g=0;g<e.length;g++)e[g]="NUM="+Object.keys(d[g]).length.toString(16)+e[g]}catch(t){console.log("[ "+t.message+" ] "+t.stack);debugger}return{blockArray:d,blockParam:e}}}},l=function(){return{value:function(a,b){var c=[],d={},e=0,f=-1,g=0,h="";try{for(key in b){var k=
b[key].partsId;h!==k&&(f++,g=0,c[f]=[],d[f]={partsType:b[key].partsType,partsId:b[key].partsId,keepObj:b[key].keepObj},h=k);c[f][g]=a[e];d[f][g]=b[key];e++;g++}}catch(v){console.log("[ "+v.message+" ] "+v.stack);debugger}return{Data:c,Parts:d}}}};return function(){Object.defineProperties(this,{length:d(),blockCount:f(),setData:g(),setDataArray:e(),getData:k(),splitRetData:l()})}}();var qtUWP=new QueTable,UWPTimerID=-1,UWPTimeoutID=0,UWPTimeoutID1st=0;
function onTimer_sampleStart(){0>=UWPTimerID&&0==UWPTimeoutID1st&&(-1!=window.navigator.userAgent.indexOf("Windows NT 10.0")&&GetHTTPCloseTimer(),UWPTimeoutID1st=setTimeout(function(){validate(null,updateInterval,"updateInterval",{numbered:!0,integer:!0,lower:5,upper:120})||(updateInterval=5);UWPTimerID=setInterval(onTimer_sampleMain,1E3*updateInterval);onTimer_sampleMain()},1))}
function onTimer_sampleMain(){for(var a=qtUWP.getData(),b=0;b<a.blockParam.length;b++)call_sampleReadDevice(a.blockParam[b],a.blockArray[b])}
function call_sampleReadDevice(a,b){try{onTimerStopForW10();0>=UWPTimeoutID&&(UWPTimeoutID=setTimeout(function(){location.href="http://"+location.host},6E4*DEF_TIMEOUT_MIN));var c=new XMLHttpRequest;c.open("POST",CGI_RD_DEV_RND,!0);c.setRequestHeader(HDTYP,HDVAL);c.send(a);c.onreadystatechange=function(){try{if(0>=UWPTimeoutID&&(clearTimeout(UWPTimeoutID),UWPTimeoutID=0),3==c.readyState&&onTimerStartForW10(),4===c.readyState)if(200!==c.status)renderSingleMessage(null,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE);
else{var a=JSON.parse(c.response);switch(a.RET){case "0000":var f=qtUWP.splitRetData(a.DATA,b);for(key in f.Parts)switch(f.Parts[key].partsType){case KEY_WS_DATBLK:WSDatblk_update(f.Parts[key].partsId,f.Data[key],f.Parts[key].keepObj);break;case KEY_WS_LEVEL:WSLevel_update(f.Parts[key].partsId,f.Data[key],f.Parts[key].keepObj);break;case KEY_WS_FIGURE:WSFigure_update(f.Parts[key].partsId,f.Data[key],f.Parts[key].keepObj);break;case KEY_WS_PICTURE:WSPicture_update(f.Parts[key].partsId,f.Data[key],
f.Parts[key].keepObj);break;case KEY_WS_HSTGRP:WSHstgrp_update(f.Parts[key].partsId,f.Data[key],f.Parts[key].keepObj);break;default:console.error(formatter(getMsgStr("LOG_0004"),"partsType",f.Parts[key].partsType))}clearTimeout(UWPTimeoutID);break;default:checkResponsCode(a.RET)}}}catch(g){renderSingleMessage(null,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE),console.log(g.message)}}}catch(d){console.log(d.message)}}
function getClockData(a,b){try{onTimerStopForW10();var c=new XMLHttpRequest;c.open("POST","/cgi/GetClockData.cgi",!0);c.setRequestHeader(HDTYP,HDVAL);c.addEventListener("loadend",function(){getClockData_Response(a,c,b)}.bind(a));c.send(null)}catch(d){console.log(d.message)}}
function getClockData_Response(a,b,c){3==b.readyState&&onTimerStartForW10();if(200===b.status)try{var d=JSON.parse(b.response);if("0000"===d.RET){var f=new Date(parseInt(d.YEAR,16),parseInt(d.MONTH,16)-1,parseInt(d.DAY,16),parseInt(d.HOUR,16),parseInt(d.MIN,16),parseInt(d.SEC,16),0);c.call(a,f)}}catch(g){renderSingleMessage(a.targetId,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE)}else renderSingleMessage(a.targetId,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE)}
function getMsgStr(a,b){var c="",d="en-us";null!=dspLanguage&&"function"===typeof dspLanguage.toLowerCase&&(d=dspLanguage.toLowerCase());if(void 0!==b)switch(b){case 0:d="ja-jp";break;case 2:d="zh-cn";break;default:case 1:d="en-us"}switch(d){case "ja-jp":d=jaMsgTbl;break;case "zh-cn":d=zhMsgTbl;break;default:case "en-us":d=enMsgTbl}for(var f=0;f<d.length;f++)if(a===d[f][0]){c=d[f][1];break}return c}
function renderMessage(a,b,c){try{var d=document.createElement("pre");d.textContent=b;c&&d.classList.add(c);d.classList.add(CLASS_ERROR_MESSAGE);var f=document.getElementById(a+ID_ERR_SUFFIX);f?f.appendChild(d):getGlobalMessageArea().appendChild(d);throw Error(b);}catch(g){console.group("renderMessage"),console.log(a+" [ "+b+" ]\n"+g.stack),console.groupEnd()}}
function renderSingleMessage(a,b,c){var d=document.getElementById(a+ID_ERR_SUFFIX);d||(d=getGlobalMessageArea());var f=d.id;if(!f){var g=0;do var e="temp"+g++;while(document.getElementById(e));d.id=e}e=document.querySelectorAll("#"+d.id+" > ."+c);d.id=f;for(g=0;g<e.length;g++)e[g].parentNode.removeChild(e[g]);renderMessage(a,b,c)}
var getGlobalMessageArea=function(){var a=null;return function(){null==a&&(a=document.createElement("div"),a.classList.add(CLASS_GLOBAL_MESSAGE_AREA),document.body.appendChild(a));return a}}();
function getDevType(a){var b;switch(TYPE_CPU_SERVER){case "R":case "r":var c;c=checkDeviceName(a);b=c.resultType;if(0==c.check.name[0]||0==c.check.name[1])b="ERR";else if(0==c.check.num[0]||0==c.check.num[1])b="ERR02";return b;default:b="ERR";c=[["LCN",3,"D"],["LCS",3,"B"],["LCC",3,"B"],["LC",2,"D"],["STN",3,"W"],["STS",3,"B"],["STC",3,"B"],["ST",2,"W"],["CN",2,"W"],["CS",2,"B"],["CC",2,"B"],["C",1,"W"],["TN",2,"W"],["TS",2,"B"],["TC",2,"B"],["T",1,"W"],["LZ",2,"D"],["SD",2,"W"],["SW",2,"W"],["SM",
2,"B"],["SB",2,"B"],["BL",2,"B"],["Z",1,"W"],["R",1,"W"],["W",1,"W"],["D",1,"W"],["S",1,"B"],["F",1,"B"],["B",1,"B"],["L",1,"B"],["M",1,"B"],["Y",1,"B"],["X",1,"B"],["U1\\G",4,"W"],["U2\\G",4,"W"],["U3\\G",4,"W"],["U4\\G",4,"W"],["U5\\G",4,"W"],["U6\\G",4,"W"],["U7\\G",4,"W"],["U8\\G",4,"W"],["U9\\G",4,"W"],["UA\\G",4,"W"],["UB\\G",4,"W"],["UC\\G",4,"W"],["UD\\G",4,"W"],["UE\\G",4,"W"],["UF\\G",4,"W"],["U10\\G",5,"W"]];var d,f;try{f=new RegExp(/BL[0-9]+\\S[0-9]+$/);if(f.test(a))return"B";for(var g=
0;c.length>g;g++)if(c[g][0]==a.substr(0,c[g][1])){d=a.slice(c[g][1]);if(""==d)break;var e;a=void 0;switch(c[g][0]){case "X":case "Y":a=8;break;case "B":case "SB":case "W":case "SW":a=16;break;case "D":case "M":case "L":case "F":case "TS":case "STS":case "CS":case "LCS":case "SM":case "SD":case "R":case "Z":case "LZ":case "TC":case "TN":case "STC":case "STN":case "CC":case "CN":case "LCC":case "LCN":case "BL":a=10;break;default:a=10}e=a;f=16==e?new RegExp(/^[0-9a-fA-F]+$/):8==e?new RegExp(/^[0-7]+$/):
new RegExp(/^[0-9]+$/);f.test(d)&&(b=c[g][2]);break}}catch(k){console.log(k.message)}return b}}
function getDevName(a){switch(TYPE_CPU_SERVER){case "R":case "r":return checkDeviceName(a).device[0].deviceName;default:var b="LCN LCS LCC LC STN STS STC ST CN CS CC C TN TS TC T LZ SD SW SM SB BL Z R W D S F B L M Y X U1\\G U2\\G U3\\G U4\\G U5\\G U6\\G U7\\G U8\\G U9\\G UA\\G UB\\G UC\\G UD\\G UE\\G UF\\G U10\\G".split(" ");try{for(var c=0;b.length>c;c++)if(b[c]==a.substr(0,b[c].length))return b[c]}catch(d){console.log(d.message)}return null}}
function convertDevNotationOctToHex(a){var b=a;switch(TYPE_CPU_SERVER){case "R":case "r":break;default:0==a.indexOf("X")?(a=a.substr(a.indexOf("X")+1,a.length),a=parseInt(a,8),b="X"+a.toString(16)):0==a.indexOf("Y")&&(a=a.substr(a.indexOf("Y")+1,a.length),a=parseInt(a,8),b="Y"+a.toString(16))}return b}function convertHexToInt_16(a,b){var c=new ArrayBuffer(2),c=new DataView(c),d=parseInt(a,16);if(isNaN(d))return null;c.setUint16(0,d,!1);return b?c.getInt16(0,!1):c.getUint16(0,!1)}
function convertHexToInt_32(a,b){var c=new ArrayBuffer(4),c=new DataView(c),d=parseInt(a,16);if(isNaN(d))return null;c.setUint32(0,d,!1);return b?c.getInt32(0,!1):c.getUint32(0,!1)}function convertHexToFloat(a){var b=new ArrayBuffer(4),b=new DataView(b);a=parseInt(a,16);if(isNaN(a))return null;b.setUint32(0,a,!1);return b.getFloat32(0,!1)}function formatter(a,b){var c=arguments;return a.replace(/\{(\d+)\}/g,function(a,b){return c[parseInt(b)+1]})}
function dateToString(a){var b=a.getFullYear()+"-",b=b+(("0"+(a.getMonth()+1)).slice(-2)+"-"),b=b+(("0"+a.getDate()).slice(-2)+" "),b=b+(("0"+a.getHours()).slice(-2)+":"),b=b+(("0"+a.getMinutes()).slice(-2)+":");return b+=("0"+a.getSeconds()).slice(-2)}
function validate(a,b,c,d){var f={required:!1,numbered:!1,integer:!1,upper:null,lower:null,includeUpper:!0,includeLower:!0,pattern:null},g=!0,e=!0;for(key in f)key in d||(d[key]=f[key]);try{if(null==b)throw d.required||(e=!1),Error(formatter(getMsgStr("MSG_0002"),c));if(d.numbered){if("number"!==typeof b)throw Error(formatter(getMsgStr("MSG_0003"),c));if(d.integer&&0!==b%1)throw Error(formatter(getMsgStr("MSG_0003"),c));if("number"===typeof d.upper&&(d.upper<b||!d.includeUpper&&d.upper==b))throw Error(formatter(getMsgStr("MSG_0003"),
c));if("number"===typeof d.lower&&(d.lower>b||!d.includeLower&&d.lower==b))throw Error(formatter(getMsgStr("MSG_0003"),c));}if(null!=d.pattern&&"function"===typeof d.pattern.test&&!d.pattern.test(b))throw Error(formatter(getMsgStr("MSG_0003"),c));}catch(k){e&&(console.log(k.message),renderMessage(a,k.message)),g=!1}finally{return g}}
function validateHighLow(a,b,c,d,f,g,e){var k=!0;validateNumber(a,b,f,e,!0)||(k=!1);validateNumber(a,c,g,e,!0)||(k=!1);k&&(b<c||!d&&b==c)&&(console.error(formatter(getMsgStr("MSG_0005"),f,g)),renderMessage(a,formatter(getMsgStr("MSG_0005"),f,g)),k=!1);return k}
function validateNumber(a,b,c,d,f){f={required:f?!0:!1,numbered:!0,lower:null,upper:null};var g=!0,e=!0;switch(d){case 0:f.lower=-32768;f.upper=32767;break;case 1:f.lower=0;f.upper=65535;break;case 2:f.lower=-2147483648;f.upper=2147483647;break;case 3:f.lower=0;f.upper=4294967295;break;case 4:f.lower=-3.4028230607370965E38;f.upper=3.4028230607370965E38;e=!1;break;case 5:switch(TYPE_CPU_SERVER){case "R":case "r":f.lower=-1.7976931348623157E308;f.upper=1.7976931348623157E308;e=!1;break;default:console.error(formatter(getMsgStr("LOG_0004"),
"format",d))}break;case 6:f.lower=0;f.upper=1;break;default:console.error(formatter(getMsgStr("LOG_0004"),"format",d))}if(1==e)try{1<b.toString().split(".").length&&(g=!1)}catch(k){g=!1}1==g?g=validate(a,b,c,f):renderMessage(a,formatter(getMsgStr("MSG_0003"),c));return g}function validateElementId(a,b){return document.getElementById(a)?!0:(console.error(formatter(getMsgStr("MSG_0001"),b)),renderMessage(a,formatter(getMsgStr("MSG_0001"),b)),!1)}
function createPartsBase(a){var b=document.createElement("div");b.id=a+document.body.childElementCount;b.classList.add(CLASS_PARTS_BASE);document.body.appendChild(b);a=document.createElement("div");a.id=b.id+ID_ERR_DISP_BTN_SUFFIX;a.textContent="!";a.classList.add(CLASS_ERROR_BUTTON);a.onclick=function(){c.style.display="none"==c.style.display?"":"none"};document.body.appendChild(a);var c=document.createElement("div");c.id=b.id+ID_ERR_SUFFIX;c.classList.add(CLASS_ERROR_FIELD);c.style.display="none";
document.body.appendChild(c);return b.id}function setPartsPos(a,b,c,d){var f={x:0,y:0};void 0!==d&&(f=d);if(d=document.getElementById(a))d.style.left=b+f.x+"px",d.style.top=c+f.y+"px";if(d=document.getElementById(a+ID_ERR_DISP_BTN_SUFFIX))d.style.left=b+"px",d.style.top=c+"px";if(d=document.getElementById(a+ID_ERR_SUFFIX))d.style.left=b+"px",d.style.top=c+"px"}
function updateErrorDispButtonState(a){var b=document.getElementById(a+ID_ERR_SUFFIX);if(b){var c=document.getElementById(a+ID_ERR_DISP_BTN_SUFFIX);c?0<b.childElementCount?c.style.display="":(b.style.display="none",c.style.display="none"):console.error(formatter(getMsgStr("LOG_0006"),a+ID_ERR_DISP_BTN_SUFFIX))}else console.error(formatter(getMsgStr("LOG_0006"),a+ID_ERR_SUFFIX))}
function onTimerStartForW10(){onTimerStopForW10();HTTPcloseTM_W10<=1E3*updateInterval&&(timerID_W10=setInterval(ReqCgiForW10,.5*HTTPcloseTM_W10))}function onTimerStopForW10(){timerID_W10&&(clearInterval(timerID_W10),timerID_W10=0)}function ReqCgiForW10(){try{var a;onTimerStopForW10();a=new XMLHttpRequest;a.open("POST","/cgi/RdDevBlk.cgi",!0);a.setRequestHeader(HDTYP,HDVAL);a.onreadystatechange=function(){ReqCgiForW10_Response(a)};a.send(null)}catch(b){console.log(b.message)}}
function ReqCgiForW10_Response(a){}function GetHTTPCloseTimer(){try{var a;a=new XMLHttpRequest;a.open("POST","/cgi/RdDevBlk.cgi",!0);a.setRequestHeader(HDTYP,HDVAL);a.onreadystatechange=function(){GetHTTPCloseTimer_Response(a)};a.send("NUM=1&DEV=SD11075")}catch(b){console.log(b.message)}}function GetHTTPCloseTimer_Response(a){try{if(4==a.readyState&&200==a.status){var b=JSON.parse(a.response);HTTPcloseTM_W10="0000"===b.RET?100*parseInt(b.DATA[0],16):9999999}}catch(c){console.log(c.message)}}
function WSDatblk(a){var b=new _WSDatblk;for(key in a)switch(key){case "dev":for(var c=0;c<a[key].length&&c<b.DATA_MAX;c++)for(key_2 in a[key][c])switch(key_2){case "dsp":b.dev[c].dsp=a[key][c][key_2];break;case "name":b.dev[c].name=a[key][c][key_2];break;case "base":b.dev[c].base=null!=a[key][c][key_2]&&null!=a[key][c][key_2].toUpperCase?a[key][c][key_2].toUpperCase():a[key][c][key_2];break;case "format":b.dev[c].format=a[key][c][key_2];break;default:console.error(formatter(getMsgStr("LOG_0006"),
key_2))}break;case "direction":b.direction=a[key];break;case "blkSize":b.blkSize=a[key];break;case "devNamDisp":b.devNamDisp=a[key];break;case "devNamCol":b.devNamCol=a[key];break;case "devNamBkCol":b.devNamBkCol=a[key];break;case "devNamWidth":b.devNamWidth=a[key];break;case "devNamHeight":b.devNamHeight=a[key];break;case "devValCol":b.devValCol=a[key];break;case "devValBkCol":b.devValBkCol=a[key];break;case "devValWidth":b.devValWidth=a[key];break;case "devValHeight":b.devValHeight=a[key];break;
case "lnCol":b.lnCol=a[key];break;case "xPos":b.xPos=a[key];break;case "yPos":b.yPos=a[key];break;default:console.error(formatter(getMsgStr("LOG_0006"),key))}setTimeout(function(){b.start()},1)}
var _WSDatblk=function(){function a(){this.type_=this.format=this.base=this.name=this.dsp=null;this.enable_=!1}this.DATA_MAX=32;this.CLASS_PARTS="datblk";this.CLASS_DEV_NAME="datblk_name";this.CLASS_DEV_VAL="datblk_val";this.targetId=null;this.dev=[];for(var b=0;b<this.DATA_MAX;b++)this.dev[b]=new a;this.yPos=this.xPos=this.lnCol=this.devValHeight=this.devValWidth=this.devValBkCol=this.devValCol=this.devNamHeight=this.devNamWidth=this.devNamBkCol=this.devNamCol=this.devNamDisp=this.blkSize=this.direction=
null;this.devNum_=this.lastDevIdx_=0;this.partsElement_=null};
_WSDatblk.prototype.start=function(){try{this.targetId=createPartsBase(KEY_WS_DATBLK),console.group("_WSDatblk:id="+this.targetId),!0===this.validateParam()&&(null!==this.partsElement_&&(console.error(getMsgStr("LOG_0002")),this.partsElement_.parentNode.removeChild(this.partsElement_)),this.partsElement_=this.create(),this.renderStyle(),this.setRequest())}catch(a){console.log(a.message)}finally{setPartsPos(this.targetId,this.xPos,this.yPos),updateErrorDispButtonState(this.targetId),console.groupEnd()}};
_WSDatblk.prototype.validateParam=function(){var a=!0;validate(this.targetId,this.xPos,"xPos",{numbered:!0})||(this.xPos=0);validate(this.targetId,this.yPos,"yPos",{numbered:!0})||(this.yPos=0);validate(this.targetId,this.direction,"direction",{numbered:!0,integer:!0,lower:0,upper:1})||(this.direction=0);validate(this.targetId,this.blkSize,"blkSize",{required:!0,numbered:!0,integer:!0,lower:1,upper:32})||(a=!1);validate(this.targetId,this.devNamDisp,"devNamDisp",{numbered:!0,integer:!0,lower:0,upper:1})||
(this.devNamDisp=1);1===this.devNamDisp&&(0===this.direction?validate(this.targetId,this.devNamWidth,"devNamWidth",{required:!0,numbered:!0,lower:0,includeLower:!1})||(a=!1):validate(this.targetId,this.devNamHeight,"devNamHeight",{required:!0,numbered:!0,lower:0,includeLower:!1})||(a=!1));validate(this.targetId,this.devValWidth,"devValWidth",{required:!0,numbered:!0,lower:0,includeLower:!1})||(a=!1);validate(this.targetId,this.devValHeight,"devValHeight",{required:!0,numbered:!0,lower:0,includeLower:!1})||
(a=!1);console.group("dev");for(var b=this.devNum_=0;b<this.dev.length&&b<this.DATA_MAX;b++){var c;c=this.dev[b];var d=b;if(null==c.dsp&&null==c.name&&null==c.base&&null==c.format)c=!1;else{var f=!0;validate(this.targetId,c.dsp,"dev["+d+"].dsp",{required:1===this.devNamDisp})||(c.dsp="","R"===TYPE_CPU_SERVER.toUpperCase()&&(f=!1));if(validate(this.targetId,c.name,"dev["+d+"].name",{required:!0})){var g=getDevType(c.name);switch(TYPE_CPU_SERVER){case "R":case "r":"ERR"===g?(renderMessage(this.targetId,
formatter(getMsgStr("MSG_0011"))),f=!1):"ERR02"===g&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0012"))),f=!1);break;default:"ERR"===g&&(console.error(formatter(getMsgStr("MSG_0003"),"dev["+d+"].name")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"dev["+d+"].name")),f=!1)}}else f=!1;validate(this.targetId,c.base,"dev["+d+"].base",{required:!0,pattern:/^[BKH]$/})||(f=!1);if(validate(this.targetId,c.format,"dev["+d+"].format",{required:!0,numbered:!0}))switch(c.format){case 0:case 1:c.type_=
"W";break;case 2:case 3:case 4:c.type_="D";break;case 5:switch(TYPE_CPU_SERVER){case "R":case "r":c.type_="Q";break;default:console.error(formatter(getMsgStr("MSG_0003"),"dev["+d+"].format")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"dev["+d+"].format")),f=!1}break;case 6:c.type_="B";break;default:console.error(formatter(getMsgStr("MSG_0003"),"dev["+d+"].format")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"dev["+d+"].format")),f=!1}else f=!1;if(f)try{if(0==compCheckType(c.name,
c.format))throw Error(formatter(getMsgStr("MSG_0006"),c.name));switch(c.format){case 0:case 1:case 2:case 3:if("B"===c.base)throw Error(formatter(getMsgStr("MSG_0006"),c.name));break;case 4:if("K"!==c.base)throw Error(formatter(getMsgStr("MSG_0006"),c.name));break;case 5:if("K"!==c.base)throw Error(formatter(getMsgStr("MSG_0006"),c.name));break;case 6:if("B"!==c.base)throw Error(formatter(getMsgStr("MSG_0006"),c.name));}}catch(e){console.error(e.message),renderMessage(this.targetId,e.message),f=!1}c=
f}c&&(this.dev[b].enable_=!0,this.lastDevIdx_=b+1,this.devNum_++)}this.DATA_MAX<this.dev.length?(console.error(formatter(getMsgStr("MSG_0003"),"length")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"dev"))):0>=this.devNum_&&(console.error(formatter(getMsgStr("MSG_0003"),"devNum_")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"dev")),a=!1);console.groupEnd();return a};
_WSDatblk.prototype.create=function(){var a,b,c=document.createElement("table");c.classList.add(this.CLASS_PARTS);a=this.blkSize;b=Math.ceil(this.lastDevIdx_/a);1===this.devNamDisp&&(b*=2);if(1===this.direction){var d;d=a;a=b;b=d}for(d=0;d<a;d++)for(var f=c.insertRow(-1),g=0;g<b;g++){var e=1===this.direction?d:g,k=Math.floor(e/2)*this.blkSize+(1===this.direction?g:d),l=f.insertCell(-1);1===this.devNamDisp&&0===e%2?(l.classList.add(this.CLASS_DEV_NAME),this.lastDevIdx_>k&&!0===this.dev[k].enable_&&
(l.textContent=this.dev[k].dsp)):l.classList.add(this.CLASS_DEV_VAL)}e=document.getElementById(this.targetId);e.insertBefore(c,e.firstChild);return c};
_WSDatblk.prototype.renderStyle=function(){var a;this.partsElement_.style.borderColor=this.lnCol;a=this.partsElement_.getElementsByClassName(this.CLASS_DEV_NAME);for(var b=0;b<a.length;b++){var c=a.item(b).style;c.color=this.devNamCol;c.backgroundColor=this.devNamBkCol;c.width=1===this.direction?this.devValWidth+"px":this.devNamWidth+"px";c.minWidth=c.width;c.maxWidth=c.width;c.height=0===this.direction?this.devValHeight+"px":this.devNamHeight+"px";c.minHeight=c.height;c.maxHeight=c.height;c.borderColor=
this.lnCol}a=this.partsElement_.getElementsByClassName(this.CLASS_DEV_VAL);for(b=0;b<a.length;b++)c=a.item(b).style,c.color=this.devValCol,c.backgroundColor=this.devValBkCol,c.width=this.devValWidth+"px",c.minWidth=c.width,c.maxWidth=c.width,c.height=this.devValHeight+"px",c.minHeight=c.height,c.maxHeight=c.height,c.borderColor=this.lnCol};
_WSDatblk.prototype.setRequest=function(){for(var a=[],b=0,c=0;c<this.lastDevIdx_;c++)!0===this.dev[c].enable_&&(a.push([convertDevNotationOctToHex(this.dev[c].name),this.dev[c].type_]),b++);b!==this.devNum_&&console.error(formatter(getMsgStr("LOG_0003"),"devNum_","enable devices",this.devNum_,b));qtUWP.setDataArray(this.targetId,KEY_WS_DATBLK,a,this);onTimer_sampleStart()};
_WSDatblk.prototype.renderDevVal=function(a){try{console.group("_WSDatblk:id="+this.targetId);a.length!==this.devNum_&&console.error(formatter(getMsgStr("LOG_0003"),"devNum_","response devices",this.devNum_,a.length));for(var b=0,c=0;b<this.lastDevIdx_&&c<a.length;b++)if(!0===this.dev[b].enable_){var d=b%this.blkSize,f=Math.floor(b/this.blkSize);1===this.devNamDisp&&(f=2*f+1);if(1===this.direction){var g;g=d;d=f;f=g}var e="";switch(this.dev[b].base){case "B":switch(this.dev[b].format){case 6:e=1==
a[c]?"1":"0";break;default:console.error(formatter(getMsgStr("LOG_0004"),"format",this.dev[b].format))}break;case "K":switch(this.dev[b].format){case 0:e=convertHexToInt_16(a[c],!0);e=null==e?"":e.toString();break;case 1:e=convertHexToInt_16(a[c],!1);e=null==e?"":e.toString();break;case 2:e=convertHexToInt_32(a[c],!0);e=null==e?"":e.toString();break;case 3:e=convertHexToInt_32(a[c],!1);e=null==e?"":e.toString();break;case 4:e=convertHexToFloat(a[c]);e=null==e?"":e.toPrecision(7);break;case 5:e=convertHexToDouble(a[c]);
e=null==e?"":e.toPrecision(15);break;default:console.error(formatter(getMsgStr("LOG_0004"),"format",this.dev[b].format))}break;case "H":switch(this.dev[b].format){case 0:case 1:e="H"+("000"+a[c]).slice(-4).toUpperCase();break;case 2:case 3:case 4:e="H"+("0000000"+a[c]).slice(-8).toUpperCase();break;case 5:e="H"+("00000000000000"+a[c]).slice(-15).toUpperCase();break;default:console.error(formatter(getMsgStr("LOG_0004"),"format",this.dev[b].format))}break;default:console.error(formatter(getMsgStr("LOG_0004"),
"base",this.dev[b].base))}this.partsElement_.rows[d].cells[f].textContent=e;c++}}catch(k){console.log(k.message)}finally{updateErrorDispButtonState(this.targetId),console.groupEnd()}};function WSDatblk_update(a,b,c){"function"===typeof c.renderDevVal?c.renderDevVal(b):console.error(formatter(getMsgStr("LOG_0006"),"renderDevVal()"))}
function WSHstgrp(a){var b=new _WSHstgrp;for(key in a)switch(key){case "grElmNum":b.grElmNum=a[key];break;case "grElm":for(var c=0;c<a[key].length&&c<b.DATA_MAX;c++)for(key_2 in a[key][c])switch(key_2){case "devName":b.grElm[c].devName=a[key][c][key_2];break;case "lnCol":b.grElm[c].lnCol=a[key][c][key_2];break;default:console.error(formatter(getMsgStr("LOG_0006"),key_2))}break;case "devFormat":b.devFormat=a[key];break;case "grBkCol":b.grBkCol=a[key];break;case "dspCol":b.dspCol=a[key];break;case "pointNum":b.pointNum=
a[key];break;case "pointInt":b.pointInt=a[key];break;case "upper":b.upper=a[key];break;case "lower":b.lower=a[key];break;case "yLine":b.yLine=a[key];break;case "xLine":b.xLine=a[key];break;case "grHeight":b.grHeight=a[key];break;case "grWidth":b.grWidth=a[key];break;case "upperMargin":b.upperMargin=a[key];break;case "leftMargin":b.leftMargin=a[key];break;case "lowerMargin":b.lowerMargin=a[key];break;case "rightMargin":b.rightMargin=a[key];break;case "xPos":b.xPos=a[key];break;case "yPos":b.yPos=a[key];
break;default:console.error(formatter(getMsgStr("LOG_0006"),key))}setTimeout(function(){b.start()},1)}
var _WSHstgrp=function(){function a(){this.lnCol=this.devName=null}this.SVGNS="http://www.w3.org/2000/svg";this.CLASS_PARTS="hstgrp";this.CLASS_FRAME="hstgrp_frame";this.CLASS_TEXT_X="hstgrp_text_x";this.CLASS_TEXT_Y="hstgrp_text_y";this.CLASS_LINE="hstgrp_line";this.ID_CLIP_PATH_SUFIX="_clip_graphFrame";this.DATA_MAX=32;this.grElmNum=this.targetId=null;this.grElm=[];for(var b=0;b<this.DATA_MAX;b++)this.grElm[b]=new a;this.clientDate_=this.serverDate_=this.lineGroup_=this.textYGroup_=this.textXGroup_=
this.frameGroup_=this.partsElement_=this.yPos=this.xPos=this.rightMargin=this.lowerMargin=this.leftMargin=this.upperMargin=this.grWidth=this.grHeight=this.xLine=this.yLine=this.lower=this.upper=this.pointInt=this.pointNum=this.dspCol=this.grBkCol=this.type_=this.devFormat=null;this.savedata_=[];for(b=0;b<this.DATA_MAX;b++)this.savedata_[b]=[]};
_WSHstgrp.prototype.start=function(){try{this.targetId=createPartsBase(KEY_WS_HSTGRP),console.group("_WSHstgrp:id="+this.targetId),!0===this.validateParam()&&(null!==this.partsElement_&&(console.error(getMsgStr("LOG_0002")),this.partsElement_.parentNode.removeChild(this.partsElement_)),this.partsElement_=this.create(),this.renderStyle(),getClockData(this,function(a){this.serverDate_=a;this.serverDate_.setMilliseconds(500);this.clientDate_=new Date}),this.setRequest())}catch(a){console.log(a.message)}finally{setPartsPos(this.targetId,
this.xPos,this.yPos),updateErrorDispButtonState(this.targetId),console.groupEnd()}};
_WSHstgrp.prototype.validateParam=function(){var a=!0,b=!0;validate(this.targetId,this.xPos,"xPos",{numbered:!0})||(this.xPos=0);validate(this.targetId,this.yPos,"yPos",{numbered:!0})||(this.yPos=0);if(validate(this.targetId,this.devFormat,"devFormat",{required:!0,numbered:!0}))switch(this.devFormat){case 0:case 1:this.type_="W";break;case 2:case 3:case 4:this.type_="D";break;case 5:switch(TYPE_CPU_SERVER){case "R":case "r":this.type_="Q";break;default:console.error(formatter(getMsgStr("MSG_0003"),
"devFormat")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"devFormat")),b=a=!1}break;case 6:this.type_="B";break;default:console.error(formatter(getMsgStr("MSG_0003"),"devFormat")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"devFormat")),b=a=!1}else b=a=!1;if(validate(this.targetId,this.grElmNum,"grElmNum",{required:!0,numbered:!0,integer:!0,lower:1,upper:this.DATA_MAX})){console.group("grElm");for(var c=0;c<this.grElmNum;c++){var d=this.grElm[c],f=c,g=!0;if(validate(this.targetId,
d.devName,"grElm["+f+"].devName",{required:!0})){var e=getDevType(d.devName);switch(TYPE_CPU_SERVER){case "R":case "r":switch(e){case "ERR":renderMessage(this.targetId,formatter(getMsgStr("MSG_0011")));g=!1;break;case "ERR02":renderMessage(this.targetId,formatter("grElm["+f+"].devName "+getMsgStr("MSG_0012"))),g=!1}break;default:switch(e){case "ERR":console.error(formatter(getMsgStr("MSG_0003"),"grElm["+f+"].devName")),renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"grElm["+f+"].devName")),
g=!1}}}else g=!1;g&&null!=this.type_&&0==compCheckType(d.devName,this.devFormat)&&(console.error(formatter(getMsgStr("MSG_0006"),d.devName)),renderMessage(this.targetId,formatter(getMsgStr("MSG_0006"),d.devName)),g=!1);g||(a=!1)}console.groupEnd()}else a=!1;validate(this.targetId,this.pointNum,"pointNum",{required:!0,numbered:!0,integer:!0,lower:5,upper:100})||(a=!1);validateHighLow(this.targetId,this.upper,this.lower,!1,"upper","lower",b?this.devFormat:null)||(a=!1);validate(this.targetId,this.yLine,
"yLine",{required:!0,numbered:!0,integer:!0,lower:0,upper:99})||(a=!1);validate(this.targetId,this.xLine,"xLine",{required:!0,numbered:!0,integer:!0,lower:0,upper:99})||(a=!1);validate(this.targetId,this.grHeight,"grHeight",{required:!0,numbered:!0,lower:0,includeLower:!1})||(a=!1);validate(this.targetId,this.grWidth,"grWidth",{required:!0,numbered:!0,lower:0,includeLower:!1})||(a=!1);validate(this.targetId,this.upperMargin,"upperMargin",{numbered:!0,lower:0,includeLower:!0})||(this.upperMargin=0);
validate(this.targetId,this.leftMargin,"leftMargin",{numbered:!0,lower:0,includeLower:!0})||(this.leftMargin=0);validate(this.targetId,this.lowerMargin,"lowerMargin",{numbered:!0,lower:0,includeLower:!0})||(this.lowerMargin=0);validate(this.targetId,this.rightMargin,"rightMargin",{numbered:!0,lower:0,includeLower:!0})||(this.rightMargin=0);return a};
_WSHstgrp.prototype.create=function(){var a=document.createElementNS(this.SVGNS,"svg"),b=document.getElementById(this.targetId);b.insertBefore(a,b.firstChild);a.className.baseVal=this.CLASS_PARTS;a.style.width=this.grWidth+this.leftMargin+this.rightMargin+"px";a.style.height=this.grHeight+this.upperMargin+this.lowerMargin+"px";b=document.createElementNS(this.SVGNS,"g");a.appendChild(b);b.className.baseVal=this.CLASS_FRAME;this.frameGroup_=b;var c=document.createElementNS(this.SVGNS,"g");a.appendChild(c);
c.className.baseVal=this.CLASS_TEXT_X;this.textXGroup_=c;var d=document.createElementNS(this.SVGNS,"g");a.appendChild(d);d.className.baseVal=this.CLASS_TEXT_Y;this.textYGroup_=d;var f=document.createElementNS(this.SVGNS,"g");a.appendChild(f);f.className.baseVal=this.CLASS_LINE;f.style.clipPath="url(#"+this.targetId+this.ID_CLIP_PATH_SUFIX+")";this.lineGroup_=f;var g,e,f=document.createElementNS(this.SVGNS,"rect");b.appendChild(f);f.x.baseVal.value=this.leftMargin;f.y.baseVal.value=this.upperMargin;
f.width.baseVal.value=this.grWidth;f.height.baseVal.value=this.grHeight;f.style.fill="none";var k=document.createElementNS(this.SVGNS,"defs");b.appendChild(k);var l=document.createElementNS(this.SVGNS,"clipPath");k.appendChild(l);l.id=this.targetId+this.ID_CLIP_PATH_SUFIX;k=document.createElementNS(this.SVGNS,"rect");l.appendChild(k);k.x.baseVal.value=this.leftMargin;k.y.baseVal.value=this.upperMargin;k.width.baseVal.value=this.grWidth;k.height.baseVal.value=this.grHeight;l=f.x.baseVal.value;k=f.y.baseVal.value+
f.height.baseVal.value;e=document.createElementNS(this.SVGNS,"text");c.appendChild(e);e.textContent="XXXX-XX-XX XX:XX:XX";g=a.createSVGLength();g.value=l;e.x.baseVal.appendItem(g);g=a.createSVGLength();g.value=k;e.y.baseVal.appendItem(g);e.style.textAnchor="start";if(0!==this.yLine)for(e=f.width.baseVal.value/(this.pointNum-2+1),g=1;g<=this.pointNum-2;g++){var h=document.createElementNS(this.SVGNS,"line");h.x1.baseVal.value=l+e*g;h.y1.baseVal.value=k;h.x2.baseVal.value=h.x1.baseVal.value;h.y2.baseVal.value=
h.y1.baseVal.value-f.height.baseVal.value;0===g%this.yLine&&b.appendChild(h)}e=document.createElementNS(this.SVGNS,"text");c.appendChild(e);e.textContent="XXXX-XX-XX XX:XX:XX";g=a.createSVGLength();g.value=l+f.width.baseVal.value;e.x.baseVal.appendItem(g);g=a.createSVGLength();g.value=k;e.y.baseVal.appendItem(g);e.style.textAnchor="end";c=c.getElementsByTagName("text");for(g=0;g<c.length;g++)e=c[g],h=e.getBBox(),h=parseInt(e.getAttribute("y"))-h.y,e.setAttribute("transform","translate(0, "+h+")");
e=document.createElementNS(this.SVGNS,"text");d.appendChild(e);e.textContent=4==this.devFormat||5==this.devFormat?this.lower.toExponential(6):this.lower;g=a.createSVGLength();g.value=l;e.x.baseVal.appendItem(g);g=a.createSVGLength();g.value=k;e.y.baseVal.appendItem(g);e.style.textAnchor="end";h=e.getBBox();h=parseInt(e.getAttribute("y"))-h.y-h.height;e.setAttribute("transform","translate(0, "+h+")");if(0!==this.xLine)for(e=f.height.baseVal.value/(this.xLine+1),g=1;g<=this.xLine;g++)h=document.createElementNS(this.SVGNS,
"line"),b.appendChild(h),h.x1.baseVal.value=l,h.y1.baseVal.value=k-e*g,h.x2.baseVal.value=h.x1.baseVal.value+f.width.baseVal.value,h.y2.baseVal.value=h.y1.baseVal.value;e=document.createElementNS(this.SVGNS,"text");d.appendChild(e);e.textContent=4==this.devFormat||5==this.devFormat?this.upper.toExponential(6):this.upper;g=a.createSVGLength();g.value=l;e.x.baseVal.appendItem(g);g=a.createSVGLength();g.value=k-f.height.baseVal.value;e.y.baseVal.appendItem(g);e.style.textAnchor="end";h=e.getBBox();h=
parseInt(e.getAttribute("y"))-h.y;e.setAttribute("transform","translate(0, "+h+")");return a};_WSHstgrp.prototype.renderStyle=function(){null!=this.grBkCol&&(this.frameGroup_.childNodes[0].style.fill=this.grBkCol);null!=this.dspCol&&(this.textXGroup_.style.fill=this.dspCol,this.textYGroup_.style.fill=this.dspCol)};
_WSHstgrp.prototype.setRequest=function(){for(var a=[],b=0,c=0;c<this.grElmNum;c++)a.push([convertDevNotationOctToHex(this.grElm[c].devName),this.type_]),b++;qtUWP.setDataArray(this.targetId,KEY_WS_HSTGRP,a,this);onTimer_sampleStart()};
_WSHstgrp.prototype.renderGraph=function(a){function b(a){this.value=a;this.date=new Date}try{for(console.group("_WSHstgrp:id="+this.targetId);this.lineGroup_.firstChild;)this.lineGroup_.removeChild(this.lineGroup_.firstChild);for(var c=this.leftMargin,d=this.upperMargin+this.grHeight,f=this.grWidth/(this.pointNum-2+1),g=this.grHeight/2/(this.upper/2-this.lower/2),e=0;e<this.grElmNum;e++){var k=null;switch(this.devFormat){case 0:k=convertHexToInt_16(a[e],!0);break;case 1:k=convertHexToInt_16(a[e],
!1);break;case 2:k=convertHexToInt_32(a[e],!0);break;case 3:k=convertHexToInt_32(a[e],!1);break;case 4:k=convertHexToFloat(a[e]);break;case 5:k=convertHexToDouble(a[e]);break;case 6:k=a[e];break;default:console.error(formatter(getMsgStr("LOG_0004"),"format",this.devFormat))}this.savedata_[e].push(new b(k));this.savedata_[e].length>this.pointNum&&this.savedata_[e].shift();var l=document.createElementNS(this.SVGNS,"polyline");this.lineGroup_.appendChild(l);l.style.fill="none";l.style.stroke=this.grElm[e].lnCol;
for(var h=k=null,m=this.upperMargin-10,p=d+10,q=0;q<this.savedata_[e].length;q++)if(null!==this.savedata_[e][q].value){var t=c+f*q,n=d-(this.savedata_[e][q].value/2-this.lower/2)*g*2,w=t,u=n;if(null==k||null==h)k=t,h=n;m>n?(u=m,m<=h&&(w=k+(m-h)/(n-h)*(t-k))):p<n&&(u=p,p>=h&&(w=k+(p-h)/(n-h)*(t-k)));if(m>h&&m<=n){var r;r=this.partsElement_.createSVGPoint();r.x=k+(m-h)/(n-h)*(t-k);r.y=m;l.points.appendItem(r)}else p<h&&p>=n&&(r=this.partsElement_.createSVGPoint(),r.x=k+(p-h)/(n-h)*(t-k),r.y=p,l.points.appendItem(r));
k=t;h=n;r=this.partsElement_.createSVGPoint();r.x=w;r.y=u;l.points.appendItem(r)}null!==this.serverDate_&&null!==this.clientDate_&&(this.textXGroup_.firstChild.textContent=dateToString(new Date(this.serverDate_.getTime()+(this.savedata_[e][0].date.getTime()-this.clientDate_.getTime()))),this.textXGroup_.lastChild.textContent=dateToString(new Date(this.serverDate_.getTime()+(this.savedata_[e][this.savedata_[e].length-1].date.getTime()-this.clientDate_.getTime()))))}}catch(v){console.log(v.message)}finally{updateErrorDispButtonState(this.targetId),
console.groupEnd()}};function WSHstgrp_update(a,b,c){"function"===typeof c.renderGraph?c.renderGraph(b):console.error(formatter(getMsgStr("LOG_0006"),"renderGraph()"))}
function WSLogoutBtn(a){var b=new _WSLogoutBtn;for(key in a)switch(key){case "btnHeight":b.btnHeight=a[key];break;case "btnWidth":b.btnWidth=a[key];break;case "btnTxt":b.btnTxt=a[key];break;case "logOutBtn":b.logOutBtn=a[key];break;case "xPos":b.xPos=a[key];break;case "yPos":b.yPos=a[key];break;default:console.error(formatter(getMsgStr("LOG_0006"),key))}setTimeout(function(){b.start()},1)}
var _WSLogoutBtn=function(){this.REQ_CGI="/cgi/LogOut.cgi";this.btnWidth=this.btnHeight=this.targetId=null;this.btnTxt="";this.btnElm_=this.yPos=this.xPos=this.logOutBtn=null};
_WSLogoutBtn.prototype.start=function(){try{this.targetId=createPartsBase(KEY_WS_LOGOUT_BTN);console.group("_WSLogoutBtn:id="+this.targetId);var a=this.validateParam();switch(TYPE_CPU_SERVER){case "R":case "r":break;default:for(var b=0;b<logoutPartsList.length&&logoutPartsList[b]!==this;b++);if(!(b<logoutPartsList.length))if(logoutPartsList.length<PARTS_MAX)logoutPartsList.push(this);else{console.error(getMsgStr("MSG_0008"));renderMessage(this.targetId,getMsgStr("MSG_0008"));return}}!0===a&&(null!==
this.btnElm_&&(console.error(getMsgStr("LOG_0002")),this.btnElm_.parentNode.removeChild(this.btnElm_)),this.btnElm_=this.create(),this.renderStyle())}catch(c){console.log(c.message)}finally{setPartsPos(this.targetId,this.xPos,this.yPos),updateErrorDispButtonState(this.targetId),console.groupEnd()}};
_WSLogoutBtn.prototype.validateParam=function(){var a=!0;validate(this.targetId,this.xPos,"xPos",{numbered:!0})||(this.xPos=0);validate(this.targetId,this.yPos,"yPos",{numbered:!0})||(this.yPos=0);validate(this.targetId,this.btnHeight,"btnHeight",{required:!0,numbered:!0,lower:0,includeLower:!1})||(a=!1);validate(this.targetId,this.btnWidth,"btnWidth",{required:!0,numbered:!0,lower:0,includeLower:!1})||(a=!1);return a};
_WSLogoutBtn.prototype.create=function(){var a=document.createElement("button");a.onclick=function(){this.logout.call(this)}.bind(this);var b=document.getElementById(this.targetId);b.insertBefore(a,b.firstChild);return a};_WSLogoutBtn.prototype.renderStyle=function(){this.btnElm_.style.height=this.btnHeight+"px";this.btnElm_.style.width=this.btnWidth+"px";this.btnElm_.textContent=this.btnTxt;this.btnElm_.classList.add(this.logOutBtn||"logout_btn")};
_WSLogoutBtn.prototype.logout=function(){var a=new XMLHttpRequest;a.open("POST",this.REQ_CGI,!0);a.setRequestHeader(HDTYP,HDVAL);a.addEventListener("loadend",function(){try{if(200===a.status)try{var b=JSON.parse(a.responseText);if(b.RET)if("0000"!=b.RET)checkResponsCode(b.RET);else switch(TYPE_CPU_SERVER){case "R":case "r":location.href="http://"+location.host+"/user/Log-in_User.html";break;default:location.href="http://"+location.host+"/user/index.html"}else renderSingleMessage(this.targetId,getMsgStr("MSG_0009"),
CLASS_SINGLE_MESSAGE)}catch(c){renderSingleMessage(this.targetId,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE)}else renderSingleMessage(this.targetId,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE)}catch(c){console.log(c.message)}finally{updateErrorDispButtonState(this.targetId)}}.bind(this));a.send()};
var jaMsgTbl=[["MSG_0001",'\u6307\u5b9a\u3057\u305f\u8981\u7d20"{0}"\u304c\u5b58\u5728\u3057\u307e\u305b\u3093\u3002'],["MSG_0002",'\u8a2d\u5b9a\u5fc5\u9808\u306e\u30d1\u30e9\u30e1\u30fc\u30bf"{0}"\u304c\u8a2d\u5b9a\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002'],["MSG_0003",'\u30d1\u30e9\u30e1\u30fc\u30bf"{0}"\u306e\u8a2d\u5b9a\u5185\u5bb9\u304c\u9593\u9055\u3063\u3066\u3044\u307e\u3059\u3002'],["MSG_0004",'\u30d1\u30e9\u30e1\u30fc\u30bf"{0}"\u306e\u8a2d\u5b9a\u5185\u5bb9\u304c\u9593\u9055\u3063\u3066\u3044\u307e\u3059\u3002'],
["MSG_0005",'\u30d1\u30e9\u30e1\u30fc\u30bf"{0}"\u3001"{1}"\u306e\u8a2d\u5b9a\u5185\u5bb9\u304c\u9593\u9055\u3063\u3066\u3044\u307e\u3059\u3002'],["MSG_0006",'\u30c7\u30d0\u30a4\u30b9"{0}"\u306e\u30c7\u30fc\u30bf\u5f62\u5f0f\u304c\u4e0d\u6b63\u3067\u3059\u3002'],["MSG_0007","\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u5f62\u5f0f\u306e\u97f3\u58f0\u30d5\u30a1\u30a4\u30eb\u304c\u6307\u5b9a\u3055\u308c\u307e\u3057\u305f\u3002"],["MSG_0008","\u4f7f\u7528\u53ef\u80fd\u306a\u90e8\u54c1\u6570\u3092\u8d85\u3048\u3066\u3044\u307e\u3059\u3002"],
["MSG_0009","\u53d7\u4fe1\u30c7\u30fc\u30bf\u304c\u7570\u5e38\u3067\u3059\u3002"],["MSG_0010","\u30ed\u30b0\u30a2\u30a6\u30c8\u3055\u308c\u3066\u3044\u307e\u3059\u3002\u30ed\u30b0\u30a4\u30f3\u3057\u3066\u518d\u5ea6\u5b9f\u884c\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["MSG_0011","\u30c7\u30d0\u30a4\u30b9\u304c\u4e0d\u9069\u5207\u3067\u3059\u3002\u4ee5\u4e0b\u306e\u539f\u56e0\u304c\u8003\u3048\u3089\u308c\u307e\u3059\u3002\r\n\u30fb\u30dd\u30a4\u30f3\u30bf\u30fb\u5b9a\u6570\u7b49\u306e\u30c7\u30d0\u30a4\u30b9\r\n\u30fbCPU\u30d1\u30e9\u30e1\u30fc\u30bf\u306e\u30c7\u30d0\u30a4\u30b9\u8a2d\u5b9a\u306e\u30c7\u30d0\u30a4\u30b9\u7bc4\u56f2\u3092\u8d85\u3048\u3066\u3044\u308b\u30c7\u30d0\u30a4\u30b9\r\n\u30fb\u672a\u30b5\u30dd\u30fc\u30c8\u306e\u30c7\u30d0\u30a4\u30b9"],
["MSG_0012","\u30c7\u30d0\u30a4\u30b9No\u304c\u4e0d\u9069\u5207\u307e\u305f\u306f\u7bc4\u56f2\u5916\u3067\u3059\u3002\u30d1\u30e9\u30e1\u30fc\u30bf\u306e\u30c7\u30d0\u30a4\u30b9\u8a2d\u5b9a\u3067\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["MSG_0013","\u6307\u5b9a\u3055\u308c\u305f\u30e6\u30cb\u30c3\u30c8\u306f\u5b58\u5728\u3057\u307e\u305b\u3093\u3002\u30e6\u30cb\u30c3\u30c8\u3092\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["MSG_0014","\u8981\u6c42\u30c7\u30fc\u30bf\u306b\u8aa4\u308a\u304c\u3042\u308a\u307e\u3059\u3002"],
["MSG_0015","\u540c\u6642\u306b\u63a5\u7d9a\u53ef\u80fd\u306a\u6570\u3092\u8d85\u3048\u3066\u3044\u308b\u305f\u3081\u3001\u63a5\u7d9a\u3067\u304d\u307e\u305b\u3093\u3002\r\n\u3057\u3070\u3089\u304f\u305f\u3063\u3066\u304b\u3089\u518d\u5ea6\u63a5\u7d9a\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["MSG_0016","\u8981\u6c42\u30c7\u30fc\u30bf\u304c\u7570\u5e38\u3067\u3059\u3002\u518d\u5ea6\u5b9f\u884c\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["MSG_0017","\u30e6\u30fc\u30b6\u540d\u307e\u305f\u306f\u30d1\u30b9\u30ef\u30fc\u30c9\u304c\u4e00\u81f4\u3057\u307e\u305b\u3093\u3002"],
["MSG_0018","\u3057\u3070\u3089\u304f\u305f\u3063\u3066\u304b\u3089\u518d\u5ea6\u30e6\u30fc\u30b6\u540d\u3001\u30d1\u30b9\u30ef\u30fc\u30c9\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["MSG_0019","Error Occured."],["MSG_0020","\u8a72\u5f53\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3059\u308b\u30e6\u30cb\u30c3\u30c8\u306e\u30de\u30cb\u30e5\u30a2\u30eb\u3092\u53c2\u7167\u304f\u3060\u3055\u3044\u3002"],["MSG_0021","\u5b58\u5728\u3057\u306a\u3044\u30d6\u30ed\u30c3\u30afNo.\u3092\u6307\u5b9a\u3057\u3066\u3044\u307e\u3059\u3002\r\n\u6307\u5b9a\u3059\u308b\u30c7\u30d0\u30a4\u30b9\u3092\u78ba\u8a8d\u3057\u3001\u5b9f\u969b\u306b\u5b58\u5728\u3059\u308b\u30d6\u30ed\u30c3\u30afNo.\u3092\u6307\u5b9a\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],
["MSG_0022","\u5b58\u5728\u3057\u306a\u3044\u30b9\u30c6\u30c3\u30d7No.\u3092\u6307\u5b9a\u3057\u3066\u3044\u307e\u3059\u3002\r\n\u6307\u5b9a\u3059\u308b\u30c7\u30d0\u30a4\u30b9\u3092\u78ba\u8a8d\u3057\u3001\u5b9f\u969b\u306b\u5b58\u5728\u3059\u308b\u30b9\u30c6\u30c3\u30d7No.\u3092\u6307\u5b9a\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["LOG_0001","PostParameter[{0}]"],["LOG_0002","process called multiple times"],["LOG_0003","{0} and {1} are different[{0}={2}, {1}={3}]"],["LOG_0004","{0} is invalid[value={1}]"],
["LOG_0005","{0} is incomplete loading or unusable"],["LOG_0006","{0} does not exist"],["MSG_WTR_BTN_0001",""],["MSG_WTR_BTN_0002","\u30c7\u30d0\u30a4\u30b9[ {0} ]\u306b[ {1} ]\u3092\u66f8\u304d\u8fbc\u307f\u307e\u3059\u3002\n\u3088\u308d\u3057\u3044\u3067\u3059\u304b\uff1f\n\n\u6ce8\u610f\uff1a\n\u30b7\u30fc\u30b1\u30f3\u30b5\u306e\u5236\u5fa1\u304c\u5909\u5316\u3057\u307e\u3059\u3002\n\u5b89\u5168\u3092\u78ba\u8a8d\u306e\u4e0a\u5b9f\u884c\u3057\u3066\u304f\u3060\u3055\u3044\u3002"],["MSG_WTR_BTN_0003",
"\u66f8\u304d\u8fbc\u307f\u6a29\u9650\u304c\u3042\u308a\u307e\u305b\u3093\u3002\r\n\u66f8\u8fbc\u307f\u6a29\u9650\u306e\u3042\u308b\u30e6\u30fc\u30b6\u3067\u518d\u5ea6\u30ed\u30b0\u30aa\u30f3\u3057\uff0c\u66f8\u8fbc\u307f\u3092\u5b9f\u884c\u3057\u3066\u304f\u3060\u3055\u3044\u3002"]],enMsgTbl=[["MSG_0001","The component specified does not exist."],["MSG_0002",'The parameters "{0}" that must be set in the user part have not been set.'],["MSG_0003",'The parameter "{0}" setting is incorrect.'],["MSG_0004",
'The parameter "{0}" setting is incorrect.'],["MSG_0005",'The parameter "{0}","{1}"setting is incorrect.'],["MSG_0006",'The data format of the device "{0}" is incorrect.'],["MSG_0007","An audio file of incompatible format was specified."],["MSG_0008","The maximum number of objects has been exceeded."],["MSG_0009","The receive data contains errors."],["MSG_0010","You are logged out.  Log in and try again."],["MSG_0011","Invalid device. The following are possible causes.\r\n-Pointer or constant\r\n-Device outside the set device range of the CPU parameter\r\n-Unsupported device"],
["MSG_0012","The device no. is invalid or out of range.\r\nPlease check parameter device setting."],["MSG_0013","The specified module does not exist. Please check the module."],["MSG_0014","The request data contains errors."],["MSG_0015","Connection could not be established because the number of simultaneous connections is exceeded.  Please reconnect after a while."],["MSG_0016","Problem with the requested data.  Please try again."],["MSG_0017","The user name or password is incorrect.\r\nPlease check the user name or password and try again."],
["MSG_0018","Please wait a while, and then re-enter the user name and password."],["MSG_0019","Error Occured."],["MSG_0020","Please refer to the manual of module that the corresponding error occurred."],["MSG_0021","The block No. which does not exist has been specified.\r\nPlease specify the really existed block No. after checking the specified device."],["MSG_0022","The step No.which does not exist has been specified.\r\nPlease specify the really existed step No. after checking the specified device."],
["LOG_0001","PostParameter[{0}]"],["LOG_0002","process called multiple times"],["LOG_0003","{0} and {1} are different[{0}={2}, {1}={3}]"],["LOG_0004","{0} is invalid[value={1}]"],["LOG_0005","{0} is incomplete loading or unusable"],["LOG_0006","{0} does not exist"],["MSG_WTR_BTN_0001",""],["MSG_WTR_BTN_0002","[ {1} ] will be written to device [ {0} ]\nAre you sure you want to continue?\n\nCaution:\n  Control of the PLC may change.\n  Ensure safety before execution."],["MSG_WTR_BTN_0003","No write permission.\r\nLog on again as a user with write permission, and try again."]],
zhMsgTbl=[["MSG_0001","\u6307\u5b9a\u7684\u8981\u7d20\u4e0d\u5b58\u5728\u3002"],["MSG_0002",'\u672a\u8bbe\u7f6e\u5fc5\u987b\u8bbe\u7f6e\u7684\u53c2\u6570"{0}"\u3002'],["MSG_0003",'\u7528\u6237\u90e8\u4ef6\u7684\u53c2\u6570"{0}"\u7684\u8bbe\u7f6e\u5185\u5bb9\u4e2d\u6709\u9519\u8bef\u3002'],["MSG_0004",'\u7528\u6237\u90e8\u4ef6\u7684\u53c2\u6570"{0}"\u7684\u8bbe\u7f6e\u5185\u5bb9\u4e2d\u6709\u9519\u8bef\u3002'],["MSG_0005",'\u53c2\u6570"{0}"\u3001"{1}"\u7684\u8bbe\u7f6e\u5185\u5bb9\u4e2d\u6709\u9519\u8bef\u3002'],
["MSG_0006","\u8f6f\u5143\u4ef6\u201c{0}\u201d\u7684\u663e\u793a\u683c\u5f0f\u4e0d\u6b63\u786e\u3002"],["MSG_0007","\u6307\u5b9a\u4e86\u4e0d\u517c\u5bb9\u7684\u683c\u5f0f\u7684\u58f0\u97f3\u6587\u4ef6\u3002"],["MSG_0008","\u8d85\u8fc7\u53ef\u4f7f\u7528\u7684\u90e8\u4ef6\u6570\u3002"],["MSG_0009","\u63a5\u6536\u6570\u636e\u5f02\u5e38\u3002"],["MSG_0010","\u5df2\u6ce8\u9500\u3002\u8bf7\u767b\u5f55\u540e\u518d\u6b21\u6267\u884c\u3002"],["MSG_0011","\u8f6f\u5143\u4ef6\u4e0d\u6b63\u786e\u3002\u53ef\u80fd\u662f\u4ee5\u4e0b\u539f\u56e0\u6240\u81f4\uff1a\r\n\u30fb\u6307\u9488\u3001\u5e38\u6570\u7b49\u8f6f\u5143\u4ef6\r\n\u30fb\u8d85\u51fa\u4e86CPU\u53c2\u6570\u7684\u8f6f\u5143\u4ef6\u8bbe\u7f6e\u7684\u8f6f\u5143\u4ef6\u8303\u56f4\u7684\u8f6f\u5143\u4ef6\r\n\u30fb\u4e0d\u652f\u6301\u7684\u8f6f\u5143\u4ef6"],
["MSG_0012","\u8f6f\u5143\u4ef6\u53f7\u4e0d\u6b63\u786e\u6216\u8d85\u51fa\u8303\u56f4\u3002\r\n\u8bf7\u786e\u8ba4\u53c2\u6570\u7684\u8f6f\u5143\u4ef6\u8bbe\u7f6e\u3002"],["MSG_0013","\u6307\u5b9a\u7684\u6a21\u5757\u4e0d\u5b58\u5728\u3002\u8bf7\u786e\u8ba4\u6a21\u5757\u3002"],["MSG_0014","\u8bf7\u6c42\u6570\u636e\u6709\u8bef\u3002"],["MSG_0015","\u8d85\u51fa\u4e86\u53ef\u4ee5\u540c\u65f6\u8fde\u63a5\u7684\u6570\u91cf\uff0c\u56e0\u6b64\u65e0\u6cd5\u8fde\u63a5\u3002\u8bf7\u7a0d\u540e\u518d\u6b21\u8fde\u63a5\u3002"],
["MSG_0016","\u8bf7\u6c42\u6570\u636e\u5f02\u5e38\u3002\u8bf7\u518d\u6b21\u6267\u884c\u3002"],["MSG_0017","\u7528\u6237\u540d\u6216\u53e3\u4ee4\u4e0d\u4e00\u81f4\u3002"],["MSG_0018","\u8bf7\u7a0d\u540e\u518d\u6b21\u8f93\u5165\u7528\u6237\u540d\u548c\u53e3\u4ee4\u3002"],["MSG_0019","Error Occured."],["MSG_0020","\u8bf7\u53c2\u7167\u53d1\u751f\u76f8\u5e94\u9519\u8bef\u7684\u6a21\u5757\u7684\u624b\u518c\u3002"],["MSG_0021","\u6307\u5b9a\u4e86\u4e0d\u5b58\u5728\u7684\u5757\u53f7\u3002\r\n\u8bf7\u786e\u8ba4\u6307\u5b9a\u7684\u8f6f\u5143\u4ef6,\u5e76\u6307\u5b9a\u5b9e\u9645\u5b58\u5728\u7684\u5757\u53f7\u3002"],
["MSG_0022","\u6307\u5b9a\u4e86\u4e0d\u5b58\u5728\u7684\u6b65\u53f7\u3002\r\n\u8bf7\u786e\u8ba4\u6307\u5b9a\u7684\u8f6f\u5143\u4ef6,\u5e76\u6307\u5b9a\u5b9e\u9645\u5b58\u5728\u7684\u6b65\u53f7\u3002"],["LOG_0001","PostParameter[{0}]"],["LOG_0002","process called multiple times"],["LOG_0003","{0} and {1} are different[{0}={2}, {1}={3}]"],["LOG_0004","{0} is invalid[value={1}]"],["LOG_0005","{0} is incomplete loading or unusable"],["LOG_0006","{0} does not exist"],["MSG_WTR_BTN_0001",""],["MSG_WTR_BTN_0002",
"[ {1} ] \u5199\u5165\u8f6f\u5143\u4ef6 [ {0} ]\u3002\u786e\u5b9a\u5417\uff1f\n\n\u6ce8\u610f\uff1a\n\u53ef\u7f16\u7a0b\u63a7\u5236\u5668\u7684\u63a7\u5236\u5c06\u53d1\u751f\u53d8\u5316\u3002\u8bf7\u786e\u8ba4\u5b89\u5168\u540e\uff0c\u518d\u6b21\u6267\u884c\u3002"],["MSG_WTR_BTN_0003","\u6ca1\u6709\u8f6f\u5143\u4ef6\u5199\u5165\u6743\u9650\u3002\r\n\u8bf7\u4f7f\u7528\u6709\u5199\u5165\u4fe1\u606f\u6743\u9650\u7684\u7528\u6237\u91cd\u65b0\u767b\u5f55\u540e\uff0c\u6267\u884c\u5199\u5165\u3002"]],enumDec=
{H:16,K:10,B:2},enumDeviceType={0:"sW16",1:"usW16",2:"sDW32",3:"usDW32",4:"Float",5:"Double",6:"Bit"},deviceParamTable={X:[{},"B",16,0,12287],Y:[{},"B",16,0,12287],M:[{},"B",10,0,161882111],L:[{},"B",10,0,32767],B:[{},"B",16,0,161882111],F:[{},"B",10,0,32767],SB:[{},"B",16,0,161882111],V:[{},"B",10,0,32767],T:[{},"W",10,0,8993439],TN:[{},"W",10,0,8993439],TC:[{},"B",10,0,8993439],TS:[{},"B",10,0,8993439],LT:[{},"D",10,0,2529407],LTN:[{},"D",10,0,2529407],LTC:[{},"B",10,0,2529407],LTS:[{},"B",10,0,
2529407],ST:[{},"W",10,0,8993439],STN:[{},"W",10,0,8993439],STC:[{},"B",10,0,8993439],STS:[{},"B",10,0,8993439],LST:[{},"D",10,0,2529407],LSTN:[{},"D",10,0,2529407],LSTC:[{},"B",10,0,2529407],LSTS:[{},"B",10,0,2529407],C:[{},"W",10,0,8993439],CN:[{},"W",10,0,8993439],CC:[{},"B",10,0,8993439],CS:[{},"B",10,0,8993439],LC:[{},"D",10,0,4761215],LCN:[{},"D",10,0,4761215],LCC:[{},"B",10,0,4761215],LCS:[{},"B",10,0,4761215],D:[{},"W",10,0,10117631],W:[{},"W",16,0,10117631],SW:[{},"W",16,0,10117631],SM:[{},
"B",10,0,4095],SD:[{},"W",10,0,4095],J:[{X:[{},"B",16,0,16383],Y:[{},"B",16,0,16383],B:[{},"B",16,0,161882111],SB:[{},"B",16,0,511],W:[{},"W",16,0,131071],SW:[{},"W",16,0,511]},"",10,1,239],U:[{G:[{},"W",10,0,268435455]},"",16,0,255],U3E:[{G:[{},"W",10,0,268435455],HG:[{},"W",10,0,12287]},"",10,0,3],DX:[{},"B",16,0,4095],DY:[{},"B",16,0,4095],Z:[{},"W",10,0,23],LZ:[{},"D",10,0,11],R:[{},"W",10,0,32767],ZR:[{},"W",10,0,10027007],RD:[{},"W",10,0,680525823],BL:[{"-":[{},"B",10,0,319],S:[{},"B",10,0,
511]},"",10,0,319]};function convertHexToDouble(a){var b=new ArrayBuffer(64),b=new DataView(b),c=new ArrayBuffer(64);new DataView(c);c=null;try{hexValue1=a.substr(0,4),hexValue2=a.substr(4,4),hexValue3=a.substr(8,4),hexValue4=a.substr(12,4),b.setInt16(0,parseInt(hexValue1,16),!1),b.setInt16(2,parseInt(hexValue2,16),!1),b.setInt16(4,parseInt(hexValue3,16),!1),b.setInt16(6,parseInt(hexValue4,16),!1),c=b.getFloat64(0,!1)}catch(d){console.log(d.message)}return c}
function checkResponsCode(a){try{switch(a){case "0000":break;case "0001":0===popupFlag&&(popupFlag=1,alert(getMsgStr("MSG_0010")));switch(TYPE_CPU_SERVER){case "R":case "r":location.href="http://"+location.host+"/";break;default:location.href.toUpperCase().match(("http://"+location.host+"/user/Log-in_User.html").toUpperCase())||(location.href="http://"+location.host+"/user/index.html")}break;case "0002":renderSingleMessage(null,getMsgStr("MSG_WTR_BTN_0003"),CLASS_SINGLE_MESSAGE);break;case "4030":renderSingleMessage(null,
getMsgStr("MSG_0011"),CLASS_SINGLE_MESSAGE);break;case "4031":case "4041":renderSingleMessage(null,getMsgStr("MSG_0012"),CLASS_SINGLE_MESSAGE);break;case "4043":renderSingleMessage(null,getMsgStr("MSG_0013"),CLASS_SINGLE_MESSAGE);break;case "4005":renderSingleMessage(null,getMsgStr("MSG_0014"),CLASS_SINGLE_MESSAGE);break;case "40A7":renderSingleMessage(null,getMsgStr("MSG_0021"),CLASS_SINGLE_MESSAGE);break;case "40A8":renderSingleMessage(null,getMsgStr("MSG_0022"),CLASS_SINGLE_MESSAGE);break;default:renderSingleMessage(null,
"[ "+a+" ] : "+getMsgStr("MSG_0020"),CLASS_SINGLE_MESSAGE),console.log("Server response : "+a+" ")}}catch(b){renderSingleMessage(null,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE),console.log(b.message)}}function WSLevel(a){try{var b=new _WSLevel,c;for(c in b.param)1==c in a&&(b.param[c]=a[c]);null==b.param.upperCol&&(b.param.upperCol=b.param.levCol);null==b.param.lowerCol&&(b.param.lowerCol=b.param.levCol)}catch(d){console.log(d.message)}finally{setTimeout(function(){b.start()},1)}}
var _WSLevel=function(){this.targetId=null;this.defaultParam={devName:null,direction:0,levCol:"blue",upperCol:null,lowerCol:null,bkCol:"white",upperVal:null,lowerVal:null,upperAlmVal:null,lowerAlmVal:null,dspAlmLn:1,almLnCol:"black",levLength:null,levWidth:null,dspVal:1,valFormat:0,devValCol:"black",devValBkCol:"white",devValWidth:null,devValHeight:null,xPos:0,yPos:0};this.ValFormatString="";this.SlideValue={range:0,rangeAlert:0};this.dispAlermLine={disp:!0,upper:!0,lower:!0};this.param=JSON.parse(JSON.stringify(this.defaultParam));
this.DirectionTag=[{low:"bottom",height:"top"},{low:"left",height:"right"}]};_WSLevel.prototype.setRequest=function(){var a=convertDevNotationOctToHex(this.param.devName);qtUWP.setData(this.targetId,KEY_WS_LEVEL,a,this.ValFormatString,this);onTimer_sampleStart()};
_WSLevel.prototype.start=function(){try{this.targetId=createPartsBase(KEY_WS_LEVEL),console.group("_WSLevel:id="+this.targetId),!0===this.validateParam()&&(this.partsElement=this.create(),this.renderStyle(),this.setRequest())}catch(a){console.log("[ "+a.message+" ] "+a.stack)}finally{setPartsPos(this.targetId,this.param.xPos,this.param.yPos),updateErrorDispButtonState(this.targetId),console.groupEnd()}};
_WSLevel.prototype.validateParam=function(){var a=!0,b;for(b in this.param)if(null==this.param[b]&&null==this.defaultParam[b])renderMessage(this.targetId,formatter(getMsgStr("MSG_0002"),b)),a=!1;else if(null==this.param[b])renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),b)),a=!1;else switch(b){case "devName":var c=getDevType(this.param[b]);switch(TYPE_CPU_SERVER){case "R":case "r":switch(c){case "ERR":renderMessage(this.targetId,formatter(getMsgStr("MSG_0011")));a=!1;break;case "ERR02":renderMessage(this.targetId,
formatter(getMsgStr("MSG_0012")));a=!1;break;default:this.ValFormatString=c}default:"ERR"===c?(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"devName")),a=!1):this.ValFormatString=c}break;case "dspAlmLn":this.dispAlermLine.disp=0==this.param[b]?!1:!0;case "direction":case "dspVal":validate(this.targetId,this.param[b],b,{numbered:!0,upper:1,lower:0})||(this.param[b]=this.defaultParam[b]);break;case "upperVal":case "lowerVal":case "upperAlmVal":case "lowerAlmVal":validate(this.targetId,
this.param[b],b,{numbered:!0})||(a=!1);break;case "valFormat":switch(TYPE_CPU_SERVER){case "R":case "r":validate(this.targetId,this.param[b],b,{numbered:!0,upper:6,lower:0})||(a=!1);break;default:validate(this.targetId,this.param[b],b,{numbered:!0,upper:4,lower:0})||(a=!1)}break;case "levLength":case "levWidth":case "devValWidth":case "devValHeight":validate(this.targetId,this.param[b],b,{numbered:!0,lower:0,includeLower:!1})||(a=!1);break;case "xPos":case "yPos":validate(this.targetId,this.param[b],
b,{numbered:!0})||(this.param[b]=this.defaultParam[b])}"number"==typeof this.param.upperVal&&"number"==typeof this.param.lowerVal&&this.param.upperVal<=this.param.lowerVal&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0005"),"upperVal","lowerVal")),a=!1);if(1==this.param.dspAlmLn&&("number"==typeof this.param.upperAlmVal&&"number"==typeof this.param.lowerAlmVal&&this.param.upperAlmVal<=this.param.lowerAlmVal&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0005"),"upperAlmVal","lowerAlmVal")),
a=!1),1==a)){if(this.param.upperVal<=this.param.upperAlmVal||this.param.lowerVal>=this.param.upperAlmVal)renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"upperAlmVal")),a=this.dispAlermLine.upper=!1;if(this.param.upperVal<=this.param.lowerAlmVal||this.param.lowerVal>=this.param.lowerAlmVal)renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"lowerAlmVal")),a=this.dispAlermLine.lower=!1}if(1==a){""===rangeCheckNum(this.param.upperVal,this.param.valFormat)&&(renderMessage(this.targetId,
formatter(getMsgStr("MSG_0003"),"upperVal")),a=!1);""===rangeCheckNum(this.param.lowerVal,this.param.valFormat)&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"lowerVal")),a=!1);""===rangeCheckNum(this.param.upperAlmVal,this.param.valFormat)&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"upperAlmVal")),a=!1);""===rangeCheckNum(this.param.lowerAlmVal,this.param.valFormat)&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"lowerAlmVal")),a=!1);switch(this.param.valFormat){case 0:case 2:case 4:case 5:this.SlideValue.range=
Math.abs(this.param.lowerVal);this.SlideValue.rangeAlert=Math.abs(this.param.lowerAlmVal);break;case 1:case 3:this.SlideValue.range=0;this.SlideValue.rangeAlert=0;break;default:a=!1}0==this.dispAlermLine.upper&&0==this.dispAlermLine.lower&&(a=this.dispAlermLine.disp=!1);0==compCheckType(this.param.devName,this.param.valFormat)&&(console.error(formatter(getMsgStr("MSG_0006"),this.param.devName)),renderMessage(this.targetId,formatter(getMsgStr("MSG_0006"),this.param.devName)),a=!1)}1==a&&(this.MaxRange=
this.param.upperVal/2-this.param.lowerVal/2,this.AlertRange=this.param.upperAlmVal/2-this.param.lowerAlmVal/2,this.VPP=this.MaxRange/this.param.levLength,this.VPK=this.MaxRange/1E3,this.RangePx=2*this.AlertRange/(2*this.VPP)-1,this.LowerPosPx=2*Math.abs(Math.abs(this.param.lowerVal/2)-Math.abs(this.param.lowerAlmVal/2))/(2*this.VPP));this.ValFormatString=convFormatString(this.param.valFormat);return a};
_WSLevel.prototype.create=function(){objLevelMeter=document.createElement("div");objLevelMeterValue=document.createElement("div");objLevelMeterRange=document.createElement("div");objLevelValue=document.createElement("div");objLevelMeterValue.id=this.targetId+"_mv";objLevelMeterRange.id=this.targetId+"_r";objLevelValue.id=this.targetId+"_v";objLevelMeter.appendChild(objLevelMeterValue);objLevelMeter.appendChild(objLevelMeterRange);document.getElementById(this.targetId).appendChild(objLevelMeter);document.getElementById(this.targetId).appendChild(objLevelValue);
return{lm:objLevelMeter,lmv:objLevelMeterValue,lmr:objLevelMeterRange,lv:objLevelValue}};
_WSLevel.prototype.renderStyle=function(){document.getElementById(this.targetId).className="partsLevel";this.partsElement.lm.className="partsLevelMeter";this.partsElement.lmv.className="partsLevelMeterValue";this.partsElement.lmr.className="partsLevelMeterRange";this.partsElement.lv.className="partsLevelValue";document.getElementById(this.targetId).setAttribute("style","float:left; ;position:absolute;top:"+this.param.yPos+"px;left:"+this.param.xPos+"px;");var a="";1==this.dispAlermLine.disp&&(1==
this.dispAlermLine.upper&&(a+="border-"+this.DirectionTag[this.param.direction].height+":1px "+this.param.almLnCol+" solid;"),1==this.dispAlermLine.lower&&(a+="border-"+this.DirectionTag[this.param.direction].low+":1px "+this.param.almLnCol+" solid;"));0==this.param.direction?(this.partsElement.lm.setAttribute("style","height:"+this.param.levLength+"px; width:"+this.param.levWidth+"px; position:relative;background-color:"+this.param.bkCol+";"),this.partsElement.lmv.setAttribute("style","height:100%;width:100%;position:absolute;bottom:0;"),
this.partsElement.lmr.setAttribute("style","height:"+this.RangePx+"px;width:100%;position:absolute;bottom:"+this.LowerPosPx+"px;"+a)):(this.partsElement.lm.setAttribute("style","height:"+this.param.levWidth+"px; width:"+this.param.levLength+"px; position:relative;background-color:"+this.param.bkCol+";"),this.partsElement.lmv.setAttribute("style","height:100%;width:100%;position:absolute;bottom:0;"),this.partsElement.lmr.setAttribute("style","height:100%;width:"+this.RangePx+"px;position:absolute;left:"+
this.LowerPosPx+"px;"+a));this.partsElement.lv.setAttribute("style","width:"+this.param.devValWidth+"px;min-width:"+this.param.devValWidth+"px;height:"+this.param.devValHeight+"px;min-height:"+this.param.devValHeight+"px;background-color:"+this.param.devValBkCol+";color:"+this.param.devValCol+";text-align:center;display:table-cell;vertical-align:middle;");0==this.param.dspVal&&this.partsElement.lv.setAttribute("style","display:none;")};
_WSLevel.prototype.renderUpdate=function(a){try{var b=0,c=a[0];a="";switch(this.param.valFormat){case 0:a=convertHexToInt_16(c,!0).toString();break;case 1:a=convertHexToInt_16(c,!1).toString();break;case 2:a=convertHexToInt_32(c,!0).toString();break;case 3:a=convertHexToInt_32(c,!1).toString();break;case 4:a=convertHexToFloat(c).toPrecision(7);break;case 5:a=convertHexToDouble(c).toPrecision(15);break;default:console.error(formatter(getMsgStr("LOG_0004"),"valFormat",this.param.valFormat))}this.param.upperAlmVal<
a?b=1:this.param.lowerAlmVal>a&&(b=2);dispValuePar=(a-this.param.lowerVal)/(2*this.VPK)/10;0>dispValuePar?dispValuePar=0:100<dispValuePar&&(dispValuePar=100);0==this.param.direction?this.partsElement.lmv.style.height=dispValuePar+"%":this.partsElement.lmv.style.width=dispValuePar+"%";switch(b){case 1:this.partsElement.lmv.style.background=this.param.upperCol;break;case 2:this.partsElement.lmv.style.background=this.param.lowerCol;break;default:this.partsElement.lmv.style.background=this.param.levCol}this.partsElement.lv.innerHTML=
a}catch(d){console.log("[ "+d.message+" ] "+d.stack)}};function WSLevel_update(a,b,c){"function"===typeof c.renderUpdate?c.renderUpdate(b):console.error(formatter(getMsgStr("LOG_0006"),"renderDevVal()"))}function WSFigure(a){try{var b=new _WS_FP(KEY_WS_FIGURE),c;for(c in b.param)1==c in a&&(b.param[c]=a[c])}catch(d){console.log(d.message)}finally{setTimeout(function(){b.start()},1)}}
function WSPicture(a){try{var b=new _WS_FP(KEY_WS_PICTURE),c;for(c in b.param)1==c in a&&(b.param[c]=a[c])}catch(d){console.log(d.message)}finally{setTimeout(function(){b.start()},1)}}
var _WS_FP=function(a){switch(a){default:case KEY_WS_FIGURE:this.defaultParam={devName:null,devFormat:null,figType:null,figHeight:null,figWidth:null,defCol:null,rangeNum:null,range:[{low:null,high:null,col:null},{low:null,high:null,col:null},{low:null,high:null,col:null},{low:null,high:null,col:null},{low:null,high:null,col:null}],xPos:0,yPos:0};this.mode=KEY_WS_FIGURE;break;case KEY_WS_PICTURE:this.defaultParam={devName:null,devFormat:null,figType:"pict",pictHeight:null,pictWidth:null,defPicture:null,
rangeNum:null,range:[{low:null,high:null,picture:null},{low:null,high:null,picture:null},{low:null,high:null,picture:null},{low:null,high:null,picture:null},{low:null,high:null,picture:null}],xPos:0,yPos:0},this.mode=KEY_WS_PICTURE}this.ValFormatString="";this.flagDirection=0;this.dispMterial="";this.param=JSON.parse(JSON.stringify(this.defaultParam));this.DirectionTag=[{low:"bottom",height:"top"},{low:"left",height:"right"}]};
_WS_FP.prototype.setRequest=function(){var a=convertDevNotationOctToHex(this.param.devName);qtUWP.setData(this.targetId,this.mode,a,this.ValFormatString,this);onTimer_sampleStart()};
_WS_FP.prototype.start=function(){try{this.targetId=createPartsBase(this.mode),console.group("_WS_FP:id="+this.targetId),!0===this.validateParam()&&(this.partsElement=this.create(),this.renderStyle(),this.setRequest())}catch(c){console.log(c.message)}finally{var a={x:0,y:0};switch(this.mode){case KEY_WS_FIGURE:if(null!=this.param.figType){var b=0;try{b=this.param.figType.toLowerCase()}catch(c){b=0}switch(b){case "tri":0<this.param.figHeight&&(a.y=-1*this.param.figHeight)}}}setPartsPos(this.targetId,
this.param.xPos,this.param.yPos,a);updateErrorDispButtonState(this.targetId);console.groupEnd()}};
_WS_FP.prototype.validateParam=function(){var a=!0,b;for(b in this.param)if(null==this.param[b]&&null==this.defaultParam[b])renderMessage(this.targetId,formatter(getMsgStr("MSG_0002"),b)),a=!1;else if(null==this.param[b])renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),b)),a=!1;else switch(b){case "devName":var c=getDevType(this.param[b]);switch(TYPE_CPU_SERVER){case "R":case "r":switch(c){case "ERR":renderMessage(this.targetId,formatter(getMsgStr("MSG_0011")));a=!1;break;case "ERR02":renderMessage(this.targetId,
formatter(getMsgStr("MSG_0012")));a=!1;break;default:this.ValFormatString=c}default:"ERR"===c&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"devName")),a=!1)}break;case "figType":if(KEY_WS_FIGURE==this.mode){c=0;try{c=this.param[b].toLowerCase()}catch(f){c=0}switch(c){case "tri":case "oval":case "rect":this.param.figType=c;break;default:renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),b)),a=!1}}else this.param.figType=this.defaultParam.figType;break;case "defCol":case "defPicture":this.dispMterial=
this.param[b];switch(TYPE_CPU_SERVER){case "R":case "r":break;default:if(!/^[\x20-\x7E]+$/.test(this.dispMterial)||/^.*[(\\|:|\*|?|\"|<|>|\|)].*$/.test(this.dispMterial))renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"defPicture")),a=!1}break;case "rangeNum":validate(this.targetId,this.param[b],b,{numbered:!0,upper:5,lower:1})||(a=!1);break;case "figHeight":case "figWidth":case "pictHeight":case "pictWidth":validate(this.targetId,this.param[b],b,{numbered:!0})||(a=!1);break;case "xPos":case "yPos":validate(this.targetId,
this.param[b],b,{numbered:!0})||(this.param[b]=this.defaultParam[b]);break;case "devFormat":switch(TYPE_CPU_SERVER){case "R":case "r":validate(this.targetId,this.param[b],b,{numbered:!0,upper:6,lower:0})||(a=!1);break;default:validate(this.targetId,this.param[b],b,{numbered:!0,pattern:/^[0-46]$/})||(a=!1)}}if(0!=a)if(this.param.range.length!=this.param.rangeNum)renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"rangeNum")),a=!1;else for(c=0;c<this.param.rangeNum;c++){var d="range["+c+"]";
for(b in this.defaultParam.range[c])if(null==this.param.range[c][b])renderMessage(this.targetId,formatter(getMsgStr("MSG_0002"),d+"."+b)),a=!1;else if("picture"===b)switch(TYPE_CPU_SERVER){case "R":case "r":break;default:if(!/^[\x20-\x7E]+$/.test(this.param.range[c][b])||/^.*[(\\|:|\*|?|\"|<|>|\|)].*$/.test(this.param.range[c][b]))renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),d+".picture")),a=!1}}if(0!=a){for(c=0;c<this.param.rangeNum;c++)d="range["+c+"]",this.param.range[c].high<this.param.range[c].low&&
(renderMessage(this.targetId,formatter(getMsgStr("MSG_0005"),d+".high",d+".low")),a=!1),""===rangeCheckNum(this.param.range[c].high,this.param.devFormat)&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),d+".high")),a=!1),""===rangeCheckNum(this.param.range[c].low,this.param.devFormat)&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),d+".low")),a=!1);0==compCheckType(this.param.devName,this.param.devFormat)&&(console.error(formatter(getMsgStr("MSG_0006"),this.param.devName)),
renderMessage(this.targetId,formatter(getMsgStr("MSG_0006"),this.param.devName)),a=!1)}this.ValFormatString=convFormatString(this.param.devFormat);return a};_WS_FP.prototype.create=function(){objDynamic=document.createElement("div");objDynamic.id=this.targetId+"_d";document.getElementById(this.targetId).appendChild(objDynamic);return objDynamic};
_WS_FP.prototype.renderStyle=function(){document.getElementById(this.targetId).className="partsFigurePos";this.partsElement.className="partsFigure";var a=this.param.figHeight,b,c;switch(this.mode){default:case KEY_WS_FIGURE:b=Math.abs(this.param.figHeight);c=Math.abs(this.param.figWidth);break;case KEY_WS_PICTURE:b=Math.abs(this.param.pictHeight),c=Math.abs(this.param.pictWidth)}0>this.param.figHeight&&(this.flagDirection=1,a=0);switch(this.param.figType.toLowerCase()){case "tri":document.getElementById(this.targetId).setAttribute("style",
"float:left; position:absolute;top:"+(this.param.yPos-a)+"px;left:"+this.param.xPos+"px;");break;default:document.getElementById(this.targetId).setAttribute("style","float:left; position:absolute;top:"+this.param.yPos+"px;left:"+this.param.xPos+"px;")}switch(this.param.figType.toLowerCase()){case "tri":0==this.flagDirection?this.partsElement.setAttribute("style","width:0px;height:0px;border: "+c/2+"px transparent solid;border-bottom: "+b+"px "+this.param.defCol+" solid;border-top: "+b+"px transparent solid;"):
this.partsElement.setAttribute("style","width:0px;height:0px;border: "+c/2+"px transparent solid;border-top: "+b+"px "+this.param.defCol+" solid;border-bottom: "+b+"px transparent solid;");break;case "oval":this.partsElement.setAttribute("style","width:"+c+"px;height:"+b+"px;border-radius:"+c/2+"px / "+b/2+"px;background:"+this.param.defCol+";");break;case "rect":this.partsElement.setAttribute("style","width:"+c+"px;height:"+b+"px;background:"+this.param.defCol+";");break;case "pict":this.partsElement.setAttribute("style",
"width:"+c+"px;height:"+b+"px;background-size: 100% 100%;background-image:url("+this.param.defPicture+");")}};
_WS_FP.prototype.renderUpdate=function(a){try{var b=a[0];a="";switch(this.param.devFormat){case 0:a=convertHexToInt_16(b,!0).toString();break;case 6:case 1:a=convertHexToInt_16(b,!1).toString();break;case 2:a=convertHexToInt_32(b,!0).toString();break;case 3:a=convertHexToInt_32(b,!1).toString();break;case 4:a=convertHexToFloat(b).toPrecision(7);break;case 5:a=convertHexToDouble(b).toPrecision(15);break;default:console.error(formatter(getMsgStr("LOG_0004"),"devFormat",this.param.devFormat))}switch(this.mode){default:case KEY_WS_FIGURE:this.dispMterial=
this.param.defCol;break;case KEY_WS_PICTURE:this.dispMterial="url("+this.param.defPicture+")"}for(var c=this.param.rangeNum-1;0<=c;c--)if(a>=this.param.range[c].low&&a<=this.param.range[c].high)switch(this.mode){default:case KEY_WS_FIGURE:this.dispMterial=this.param.range[c].col;break;case KEY_WS_PICTURE:this.dispMterial="url("+this.param.range[c].picture+")"}switch(this.param.figType.toLowerCase()){case "tri":0==this.flagDirection?this.partsElement.style["border-bottom-color"]=this.dispMterial:this.partsElement.style["border-top-color"]=
this.dispMterial;break;case "oval":case "rect":this.partsElement.style["background-color"]=this.dispMterial;break;case "pict":this.partsElement.style["background-image"]=this.dispMterial}}catch(d){console.log("[ "+d.message+" ] "+d.stack)}};function WSFigure_update(a,b,c){"function"===typeof c.renderUpdate?c.renderUpdate(b):console.error(formatter(getMsgStr("LOG_0006"),"renderDevVal()"))}
function WSPicture_update(a,b,c){"function"===typeof c.renderUpdate?c.renderUpdate(b):console.error(formatter(getMsgStr("LOG_0006"),"renderDevVal()"))}var CGI_WR_DEV=CGI_HOST+"/cgi/WrDev.cgi";function WSWrtBtn(a){try{var b=new _WSWrtBtn,c;for(c in b.param)1==c in a&&(b.param[c]=a[c])}catch(d){console.log(d.message)}finally{setTimeout(function(){b.start()},1)}}
var _WSWrtBtn=function(){this.defaultParam={devName:null,devBase:null,devFormat:null,wrVal:null,wrBtn:"",btnTxt:"",btnWidth:null,btnHeight:null,wrComfirm:0,language:1,xPos:0,yPos:0,flagDebugPrint:0};this.ValWriteString=this.ValFormatString="";this.buttonDisabled=!0;this.param=JSON.parse(JSON.stringify(this.defaultParam))};
_WSWrtBtn.prototype.start=function(){try{this.targetId=createPartsBase(KEY_WS_WTR_BTN),console.group("_WSWrtBtn:id="+this.targetId),!0===this.validateParam()&&(this.buttonDisabled=!1,this.partsElement=this.create(),this.renderStyle())}catch(a){console.log(a.message)}finally{setPartsPos(this.targetId,this.param.xPos,this.param.yPos),updateErrorDispButtonState(this.targetId),console.groupEnd(),funcDebugPrint(this.param.flagDebugPrint,this.param.xPos,this.param.yPos,{devName:this.param.devName,devBase:this.param.devBase,
devFormat:enumDeviceType[this.param.devFormat],wrVal:this.param.wrVal})}};
_WSWrtBtn.prototype.validateParam=function(){var a=!0,b;for(b in this.param)if(null==this.param[b]&&null==this.defaultParam[b])renderMessage(this.targetId,formatter(getMsgStr("MSG_0002"),b)),a=!1;else if(null==this.param[b])renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),b)),a=!1;else switch(b){case "devName":var c=getDevType(this.param[b]);switch(TYPE_CPU_SERVER){case "R":case "r":switch(c){case "ERR":renderMessage(this.targetId,formatter(getMsgStr("MSG_0011")));a=!1;break;case "ERR02":renderMessage(this.targetId,
formatter(getMsgStr("MSG_0012")));a=!1;break;default:this.ValFormatString=c}default:"ERR"===c&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"devName")),a=!1)}break;case "devBase":null!=this.param[b]&&null!=this.param[b].toUpperCase&&(this.param[b]=this.param[b].toUpperCase());switch(this.param[b]){case "B":case "K":case "H":break;default:renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"devBase")),a=!1}break;case "wrComfirm":validate(this.targetId,this.param[b],b,{numbered:!0,
upper:1,lower:0})||(this.param[b]=this.defaultParam[b]);break;case "language":validate(this.targetId,this.param[b],b,{numbered:!0,upper:2,lower:0})||(this.param[b]=this.defaultParam[b]);break;case "devFormat":switch(TYPE_CPU_SERVER){case "R":case "r":validate(this.targetId,this.param[b],b,{numbered:!0,upper:6,lower:0})?this.ValFormatString=c:a=!1;break;default:validate(this.targetId,this.param[b],b,{numbered:!0,pattern:/^[0-46]$/})?this.ValFormatString=c:a=!1}break;case "wrBtn":case "btnTxt":0>=this.param[b].length&&
(this.param[b]=this.defaultParam[b]);break;case "wrVal":"string"!=typeof this.param[b]?(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"wrVal")),a=!1):(this.param[b]=this.param[b].toString(),0>=this.param[b].trim().length&&(renderMessage(this.targetId,formatter(getMsgStr("MSG_0003"),"wrVal")),a=!1));break;case "btnWidth":case "btnHeight":validate(this.targetId,this.param[b],b,{numbered:!0,lower:0,includeLower:!1})||(a=!1);break;case "xPos":case "yPos":validate(this.targetId,this.param[b],
b,{numbered:!0})||(this.param[b]=this.defaultParam[b])}1==a&&(0==compCheckType(this.param.devName,this.param.devFormat)?(console.error(formatter(getMsgStr("MSG_0006"),this.param.devName)),renderMessage(this.targetId,formatter(getMsgStr("MSG_0006"),this.param.devName)),a=!1):(b=convertInputVal(this.param.devFormat,this.param.devBase,this.param.wrVal,this.targetId,this.param.devName),""===b?a=!1:(this.ValWriteString=b,this.ValFormatString=convFormatString(this.param.devFormat))));return a};
_WSWrtBtn.prototype.create=function(){objWriteButtonBody=document.createElement("button");objWriteButtonBody.className=this.param.wrBtn;objWriteButtonBody.id=this.targetId+"_b";objWriteButtonBody.onclick=function(){this.onClickEvewnt.call(this)}.bind(this);document.getElementById(this.targetId).appendChild(objWriteButtonBody);return{buttonBody:objWriteButtonBody}};
_WSWrtBtn.prototype.onClickEvewnt=function(){if(1==this.param.wrComfirm)try{confirm(formatter(getMsgStr("MSG_WTR_BTN_0002",this.param.language),this.param.devName,this.param.wrVal))&&this.call_WriteDevice()}catch(a){console.error("confirm : [ "+a.message+" ] "+a.stack)}finally{}else this.call_WriteDevice()};
_WSWrtBtn.prototype.call_WriteDevice=function(){try{var a="",a="NUM=1&",b=convertDevNotationOctToHex(this.param.devName),a=a+("DEV1="+b+"&"),a=a+("TYP1="+this.ValFormatString+"&"),a=a+("DATA1="+this.ValWriteString),c=new XMLHttpRequest;c.open("POST",CGI_WR_DEV,!0);c.setRequestHeader(HDTYP,HDVAL);c.addEventListener("loadend",function(){if(200===c.status)try{var a=JSON.parse(c.responseText);a.RET?"0000"!=a.RET&&checkResponsCode(a.RET):renderSingleMessage(this.targetId,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE)}catch(f){renderSingleMessage(this.targetId,
getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE)}else renderSingleMessage(this.targetId,getMsgStr("MSG_0009"),CLASS_SINGLE_MESSAGE);updateErrorDispButtonState(this.targetId);console.groupEnd()}.bind(this));c.onerror=function(){2>reqRetry&&(reqRetry++,call_WriteDevice())};c.send(a)}catch(d){console.log("[ "+d.message+" ] "+d.stack)}finally{updateErrorDispButtonState(this.targetId),console.groupEnd()}};
_WSWrtBtn.prototype.renderStyle=function(){document.getElementById(this.targetId).className="partsWriteButton";0<this.param.wrBtn.length&&(this.partsElement.buttonBody.className=this.param.wrBtn);this.partsElement.buttonBody.innerHTML=this.param.btnTxt;this.partsElement.buttonBody.disabled=this.buttonDisabled;document.getElementById(this.targetId).setAttribute("style","float:left;position:absolute;top:"+this.param.yPos+"px;left:"+this.param.xPos+"px;");this.partsElement.buttonBody.setAttribute("style",
"position:relative;width:"+this.param.btnWidth+"px;height:"+this.param.btnHeight+"px;")};
function convertInputVal(a,b,c,d,f){try{var g,e="",k=1;b=b.toUpperCase();if(""==c)return renderMessage(d,formatter(getMsgStr("MSG_0003"),"wrVal")),e;switch(b){case "B":g=new RegExp(/[0-1]{1}/);switch(a){case 0:case 1:case 2:case 3:case 4:case 5:return renderMessage(d,formatter(getMsgStr("MSG_0006"),f)),e;default:return renderMessage(d,formatter(getMsgStr("MSG_0003"),"devFormat")),e;case 6:k=1}break;case "H":g=new RegExp(/^[0-9A-Fa-f]+$/);switch(a){case 0:case 1:k=1;break;case 2:case 3:k=3;break;case 4:case 5:case 6:return renderMessage(d,
formatter(getMsgStr("MSG_0006"),f)),e;default:return renderMessage(d,formatter(getMsgStr("MSG_0003"),"devFormat")),e}break;case "K":switch(a){case 0:case 2:g=new RegExp(/^[-+0-9]+$/);break;case 1:case 3:g=new RegExp(/^[+0-9]+$/);break;case 4:case 5:g=new RegExp(/^[-+.eE0-9]+$/);break;case 6:return renderMessage(d,formatter(getMsgStr("MSG_0006"),f)),e;default:return renderMessage(d,formatter(getMsgStr("MSG_0003"),"devFormat")),e}break;default:return renderMessage(d,formatter(getMsgStr("MSG_0003"),
"devBase")),e}if(g.test(c))switch(a){case 6:e=parseInt(c,2);e=rangeCheckNum(e,a);break;case 0:case 2:"K"==b?checkSigned(c,1)&&(e=parseInt(c,10),e=rangeCheckNum(e,a)):checkSigned(c,2)&&(e=parseInt(c,16),e=rangeCheckNum(e,k));break;case 1:case 3:"K"==b?checkSigned(c,1)&&(e=parseInt(c,10),e=rangeCheckNum(e,a)):checkSigned(c,0)&&(e=parseInt(c,16),e=rangeCheckNum(e,a));break;case 4:case 5:checkFloat(c)&&(e=parseFloat(c),e=rangeCheckNum(e,a));break;default:return e}else return renderMessage(d,formatter(getMsgStr("MSG_0003"),
"wrVal")),e;if(""!==e){var l=new ArrayBuffer(16),h=new DataView(l);switch(a){case 0:h.setInt16(0,e,!0);e=h.getUint16(0,!0).toString(16);e=("0000"+h.getUint16(0,!0).toString(16)).slice(-4).toUpperCase();break;case 1:h.setUint16(0,e,!0);e=h.getUint16(0,!0).toString(16);e=("0000"+h.getUint16(0,!0).toString(16)).slice(-4).toUpperCase();break;case 2:h.setInt32(0,e,!0);e=h.getUint32(0,!0).toString(16);e=("00000000"+h.getUint32(0,!0).toString(16)).slice(-8).toUpperCase();break;case 3:h.setUint32(0,e,!0);
e=h.getUint32(0,!0).toString(16);e=("00000000"+h.getUint32(0,!0).toString(16)).slice(-8).toUpperCase();break;case 4:h.setFloat32(0,e,!0);e=h.getUint32(0,!0).toString(16);e=("00000000"+h.getUint32(0,!0).toString(16)).slice(-8).toUpperCase();break;case 5:h.setFloat64(0,e,!0);var m=("00000000"+h.getUint32(0,!0).toString(16)).slice(-8).toUpperCase(),e=("00000000"+h.getUint32(4,!0).toString(16)).slice(-8).toUpperCase()+m;break;default:e=1==e?1:0}}else renderMessage(d,formatter(getMsgStr("MSG_0003"),"wrVal"))}catch(p){console.log("[ "+
p.message+" ] "+p.stack);e="";debugger}return e}function checkSigned(a,b){var c=a.length,d=!0,f=0;croppedstr="";for(1==b?"-"!=a.charAt(f)&&"+"!=a.charAt(f)||f++:2==b&&"-"==a.charAt(f)&&f++;f<c;f++)if("-"==a.charAt(f)){d=!1;break}else if("+"==a.charAt(f)){d=!1;break}else 2==b&&(croppedstr+=a.charAt(f));return d}
function checkFloat(a,b){var c=a.length,d=!0,f=0,g=a.toUpperCase(),e=0,k=0,l=0,h=0;"-"==g.charAt(f)?f++:"+"==g.charAt(f)&&f++;if(-1==g.indexOf("E",f))for(;f<c;f++)switch(g.charAt(f)){case "-":return!1;case "+":return!1;case ".":if(e++,1<e)return!1}else{for(;f<c;f++)switch(g.charAt(f)){case "-":l++;if(1<l||"E"!=g.charAt(f-1))return!1;break;case "+":h++;if(1<h||"E"!=g.charAt(f-1))return!1;break;case ".":e++;if(1<e)return!1;break;case "E":if(k++,1<k)return!1}c=g.slice(g.indexOf("E")+1,c);if(0==c.length)return!1;
c=parseInt(c,10);if(isNaN(c))return!1;switch(b){case 4:if(-38>c||38<c)d=!1;break;case 5:if(-308>c||308<c)d=!1}}return d}
function compCheckType(a,b){if("R"===TYPE_CPU_SERVER.toUpperCase()){var c=!0;try{var d=checkDeviceName(a),f=convFormatString(b);if(d.dataType!==f)switch(d.dataType){case "W":"D"!==f&&"Q"!==f&&(c=!1);break;case "D":"Q"!==f&&(c=!1);break;default:c=!1}switch(d.device[0].deviceName){case "T":case "TN":case "ST":case "STN":case "C":case "CN":1!=b&&(c=!1);break;case "LT":case "LTN":case "LST":case "LSTN":case "LC":case "LCN":3!=b&&(c=!1)}}catch(e){}}else{c=!0;try{var g=getDevType(a),f=convFormatString(b);
g===f||"W"===g&&"D"===f||(c=!1);switch(getDevName(a)){case "T":case "TN":case "ST":case "STN":case "C":case "CN":1!=b&&(c=!1);break;case "LC":case "LCN":2!=b&&3!=b&&(c=!1);break;case "LZ":2!=b&&3!=b&&4!=targetargFormat&&(c=!1)}}catch(e){console.log(e.message)}}return c}
function rangeCheckNum(a,b){var c="";if(isNaN(a))return c;switch(b){case 6:0<=a&&1>=a&&(c=a);break;case 0:-32768<=a&&32767>=a&&(c=a);break;case 1:0<=a&&65535>=a&&(c=a);break;case 2:-2147483648<=a&&2147483647>=a&&(c=a);break;case 3:0<=a&&4294967295>=a&&(c=a);break;case 4:var d=!1,c="";-3.40282347E38<=a&&-1.17549435E-38>=a&&(d=!0);0==a&&(d=!0);1.17549435E-38<=a&&3.40282347E38>=a&&(d=!0);1==d&&(c=a);break;case 5:d=!1,c="",-1.7976931348623157E308<=a&&-2.2250738585072014E-308>=a&&(d=!0),0==a&&(d=!0),2.2250738585072014E-308<=
a&&1.7976931348623157E308>=a&&(d=!0),1==d&&(c=a)}return c}function convFormatString(a){var b="";switch(a){case 0:case 1:b="W";break;case 2:case 3:case 4:b="D";break;case 5:"R"===TYPE_CPU_SERVER.toUpperCase()&&(b="Q");break;case 6:b="B"}return b}
function funcDebugPrint(a,b,c,d){if(1===a){a=document.createElement("div");a.setAttribute("style","float:left;position:absolute;top:"+c+"px;left:"+(b+40)+"px;");b="";for(var f in d)b+="<span>"+f+"&nbsp;:&nbsp;"+d[f]+"</span>&nbsp;&nbsp;/&nbsp;&nbsp;";a.innerHTML=b;document.body.appendChild(a)}}
function checkDeviceName(a){var b={dataType:0,devicePart:0,inputDevice:"",result:!1,resultType:"ERR",device:[{device:"",dlen:0,deviceName:"",deviceNum:"",nameNum:-1,nameNumMin:-1,nameNumMax:-1},{device:"",dlen:0,deviceName:"",deviceNum:"",nameNum:-1,nameNumMin:-1,nameNumMax:-1}],check:{name:[!1,!1],num:[!1,!1]}};try{b.inputDevice=a;aDev=a.split("\\");if(16>=a.length){if(0<a.length&&2>=aDev.length)for(keyDev1 in deviceParamTable)if(0==aDev[0].toLowerCase().indexOf(keyDev1.toLowerCase())){if(b.device[0].dlen<
keyDev1.length){switch(keyDev1.toLowerCase()){case "u":case "u3e":tempValue=aDev[0].substr(keyDev1.length,aDev[0].length);0<tempValue.length?(b.device[0].dlen=keyDev1.length,b.device[0].deviceName=keyDev1):(b.device[0].dlen=1,b.device[0].deviceName="u");b.device[0].deviceNum=aDev[0].substr(b.device[0].dlen,aDev[0].length);break;default:b.device[0].dlen=keyDev1.length,b.device[0].deviceName=keyDev1,b.device[0].deviceNum=aDev[0].substr(b.device[0].dlen,aDev[0].length),0>=b.device[0].deviceNum.length&&
(b.device[0].dlen=-1)}b.devicePart=1;b.dataType=deviceParamTable[keyDev1][1];b.device[0].nameNum=deviceParamTable[keyDev1][2];b.device[0].nameNumMin=deviceParamTable[keyDev1][3];b.device[0].nameNumMax=deviceParamTable[keyDev1][4];b.device[0].device=aDev[0];b.check.name[0]=!0}if(0<Object.keys(deviceParamTable[keyDev1][0]).length){b.device[1].dlen=-1;switch(keyDev1.toLowerCase()){case "bl":1==aDev.length&&(aDev[1]="-0"),b.device[0].device=aDev[0]}if(2==aDev.length){for(keyDev2 in deviceParamTable[keyDev1][0])0==
aDev[1].toLowerCase().indexOf(keyDev2.toLowerCase())&&b.device[1].dlen<keyDev2.length&&(b.device[1].dlen=keyDev2.length,b.device[1].deviceName=keyDev2,b.device[1].deviceNum=aDev[1].substr(b.device[1].dlen,aDev[1].length),0>=b.device[1].deviceNum.length&&(b.device[1].dlen=-1),b.devicePart=2,b.dataType=deviceParamTable[keyDev1][0][keyDev2][1],b.device[1].nameNum=deviceParamTable[keyDev1][0][keyDev2][2],b.device[1].nameNumMin=deviceParamTable[keyDev1][0][keyDev2][3],b.device[1].nameNumMax=deviceParamTable[keyDev1][0][keyDev2][4],
b.device[1].device=aDev[1],b.check.name[1]=!0);b.devicePart=2}}else 2<=aDev.length&&(b.device[1].dlen=-1,b.devicePart=0);switch(b.device[1].deviceName){case "-":case "":1==b.check.name[1]&&(b.devicePart=1)}}1==b.devicePart&&(b.check.name[1]=!0,b.check.num[1]=!0);for(var c=0;c<b.devicePart;c++){a="";var d=0,f=0,g=0;switch(b.device[c].nameNum){case 10:a=new RegExp(/^[0-9]+$/);f=b.device[c].nameNumMin;d=b.device[c].nameNumMax;g=b.device[c].deviceNum;break;case 16:a=new RegExp(/^[0-9a-fA-F]+$/),f=b.device[c].nameNumMin,
d=b.device[c].nameNumMax,g=parseInt(b.device[c].deviceNum,16)}1==a.test(b.device[c].deviceNum)&&f<=g&&g<=d&&(b.check.num[c]=!0)}}a=!0;0==b.devicePart&&(a=!1);for(c=0;c<b.devicePart;c++)if(0==b.check.name[c]||0==b.check.num[c]||0>=b.device[c].dlen)a=!1;b.result=a;b.resultType=0==b.result?"ERR":b.dataType}catch(e){console.log("[ "+e.message+" ] "+e.stack)}return b}var loginFlg=!1;
function loginStart(a,b,c){var d=document.getElementById(a),f=document.getElementById(b),g=document.getElementById(c);d&&f&&g&&(/^[a-zA-Z0-9 !-/:-@\u00a5[-`{-~]{1,20}$/.test(d.value)?/^[a-zA-Z0-9 !-/:-@\u00a5[-`{-~]{6,32}$/.test(f.value)?call_getRndNum(a,b,c):f.focus():d.focus())}
function call_getRndNum(a,b,c){var d=document.getElementById(c);if(!0!==loginFlg){loginFlg=!0;try{xhr=new XMLHttpRequest,xhr.open("POST","/cgi/GetRndNum.cgi",!0),xhr.setRequestHeader(HDTYP,HDVAL),xhr.addEventListener("loadend",function(){if(200===xhr.status){var f=JSON.parse(xhr.response);switch(f.RET){case "0000":call_login(f.DATA,f.NO,a,b,c);break;case "0001":d.innerText=getMsgStr("MSG_0015");loginFlg=!1;break;case "0002":d.innerText=getMsgStr("MSG_0016");loginFlg=!1;break;default:d.innerText=getMsgStr("MSG_0019"),
console.log("Server response : "+f.RET),loginFlg=!1}}}.bind(this)),xhr.send("NUM=32")}catch(f){console.log("[ "+f.message+" ] "+f.stack),loginFlg=!1}}}
function call_login(a,b,c,d,f){try{var g=document.getElementById(c),e=document.getElementById(d),k=document.getElementById(f),l=(new MyHmacSha256).hmac_sha256(e.value,a),h;h="USER="+encodeURIComponent(g.value)+"&HASH="+encodeURIComponent(l)+"&NO="+b;xhr=new XMLHttpRequest;xhr.open("POST","/cgi/login.cgi",!0);xhr.setRequestHeader(HDTYP,HDVAL);xhr.addEventListener("loadend",function(){if(200===xhr.status){var a=JSON.parse(xhr.response);switch(a.RET){case "0000":location.href=a.LOC;return;case "0001":k.innerText=
getMsgStr("MSG_0015");break;case "0003":k.innerText=getMsgStr("MSG_0017");break;case "0004":k.innerText=getMsgStr("MSG_0018");break;default:k.innerText=getMsgStr("MSG_0009"),console.log("Server response : "+a.RET)}loginFlg=!1}}.bind(this));xhr.send(h)}catch(m){console.log("[ "+m.message+" ] "+m.stack),loginFlg=!1}}function MyHmacSha256(){}
MyHmacSha256.prototype={_initHash:[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],_cnstK:[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,
1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298],_sha256proc:function(a,b){function c(a,b){return b>>>a|b<<32-a}function d(a){return c(2,a)^c(13,a)^c(22,a)}function f(a){return c(6,a)^c(11,a)^c(25,a)}function g(a){return c(7,a)^c(18,a)^
a>>>3}function e(a){return c(17,a)^c(19,a)^a>>>10}var k,l=new DataView(a),h=new Uint32Array(8),m=new DataView(b),p=new ArrayBuffer(32),q=new DataView(p),t,n,w,u,r,v,y,z,x=Array(64);for(k=0;8>k;k++)h[k]=l.getUint32(4*k,!1);l=h[0];t=h[1];n=h[2];w=h[3];u=h[4];r=h[5];v=h[6];y=h[7];for(k=0;16>k;k++)x[k]=m.getUint32(4*k,!1);for(k=16;64>k;k++)x[k]=e(x[k-2])+x[k-7]+g(x[k-15])+x[k-16];for(k=0;64>k;k++)m=y+f(u)+(u&r^~u&v)+this._cnstK[k]+x[k],z=d(l)+(l&t^l&n^t&n),y=v,v=r,r=u,u=w+m|0,w=n,n=t,t=l,l=m+z|0;q.setUint32(0,
h[0]+l|0,!1);q.setUint32(4,h[1]+t|0,!1);q.setUint32(8,h[2]+n|0,!1);q.setUint32(12,h[3]+w|0,!1);q.setUint32(16,h[4]+u|0,!1);q.setUint32(20,h[5]+r|0,!1);q.setUint32(24,h[6]+v|0,!1);q.setUint32(28,h[7]+y|0,!1);return p},hmac_sha256:function(a,b){if(!("string"==typeof a||a instanceof String)||!("string"==typeof b||b instanceof String))throw Error("TargetData or SecretKey is not string/String Object!!");if(64<a.length||64<b.length)throw Error("TargetData or SecretKey is too LONG(over 64byte)!!");if(0!=
b.length%2)throw Error("SecretKey data length is wrong(odd)!!");if(a.match(/[^\x20-\x7e]+/)||b.match(/[^0-9A-Fa-f]+/))throw Error("TargetData or SecretKey has wrong character!!");var c,d;d=new ArrayBuffer(64);var f=new Uint8Array(d),g;g=new ArrayBuffer(64);var e=new Uint8Array(g),k=new ArrayBuffer(64),l=new DataView(k),h=new ArrayBuffer(64),m=new Uint8Array(h),p=new ArrayBuffer(64),q=new Uint8Array(p);for(c=0;c<b.length/2;c++)f[c]=e[c]=parseInt(b.substring(2*c,2*c+2),16);for(c=0;64>c;c++)f[c]^=54,
e[c]^=92;for(c=0;8>c;c++)l.setUint32(4*c,this._initHash[c],!1);d=this._sha256proc(k,d);g=this._sha256proc(k,g);for(c=0;c<a.length;c++)m[c]=a.charCodeAt(c);56>a.length?(m[a.length]=128,c=8*(64+a.length),m[60]=c>>24&255,m[61]=c>>16&255,m[62]=c>>8&255,m[63]=c&255,c=this._sha256proc(d,h)):(56<=a.length&&64>a.length?m[a.length]=128:q[0]=128,c=8*(64+a.length),q[60]=c>>24&255,q[61]=c>>16&255,q[62]=c>>8&255,q[63]=c&255,c=this._sha256proc(d,h),c=this._sha256proc(c,p));c=new Uint8Array(c);p=new ArrayBuffer(64);
h=new Uint8Array(p);h.set(c,0);h[c.byteLength]=128;c=8*(64+c.byteLength);h[60]=c>>24&255;h[61]=c>>16&255;h[62]=c>>8&255;h[63]=c&255;c=this._sha256proc(g,p);p=new DataView(c);h="";for(c=0;c<p.byteLength;c++)h+=("00"+p.getUint8(c).toString(16)).slice(-2);return h}};
